import { $Level, $Level_ } from "@package/net/minecraft/world/level";
import { $InteractionResult, $InteractionHand_ } from "@package/net/minecraft/world";
import { $HolderLookup$Provider, $BlockPos } from "@package/net/minecraft/core";
import { $ServerPlayer } from "@package/net/minecraft/server/level";
import { $Item_, $ItemStack_, $ItemStack } from "@package/net/minecraft/world/item";
import { $CompoundTag } from "@package/net/minecraft/nbt";
import { $Camera } from "@package/io/github/mortuusars/exposure/world/camera";
import { $EntityDimensions, $EntityType_, $Entity$RemovalReason, $LivingEntity, $PortalProcessor, $Entity } from "@package/net/minecraft/world/entity";
import { $Player } from "@package/net/minecraft/world/entity/player";
import { $CameraItem } from "@package/io/github/mortuusars/exposure/world/item/camera";
import { $UUID, $Stack } from "@package/java/util";
import { $Vec3 } from "@package/net/minecraft/world/phys";

declare module "@package/io/github/mortuusars/exposure/world/entity" {
    export class $CameraHolder {
    }
    export interface $CameraHolder {
        getPlayerExecutingExposure(): ($Player) | undefined;
        getExposureAuthorEntity(): $Entity;
        getExposureCameraOperator(): ($CameraOperator) | undefined;
        asHolderEntity(): $Entity;
        getPlayerAwardedForExposure(): ($Player) | undefined;
        getServerPlayerAwardedForExposure(): ($ServerPlayer) | undefined;
        getServerPlayerExecutingExposure(): ($ServerPlayer) | undefined;
        get playerExecutingExposure(): ($Player) | undefined;
        get exposureAuthorEntity(): $Entity;
        get exposureCameraOperator(): ($CameraOperator) | undefined;
        get playerAwardedForExposure(): ($Player) | undefined;
        get serverPlayerAwardedForExposure(): ($ServerPlayer) | undefined;
        get serverPlayerExecutingExposure(): ($ServerPlayer) | undefined;
    }
    export class $CameraOperator {
    }
    export interface $CameraOperator {
        removeActiveExposureCamera(): void;
        setActiveExposureCamera(camera: $Camera): void;
        getActiveExposureCamera(): $Camera;
        asOperatorEntity(): $LivingEntity;
        getExposureCameraActionAnim(partialTick: number): number;
        getActiveExposureCameraOptional(): ($Camera) | undefined;
        get activeExposureCameraOptional(): ($Camera) | undefined;
    }
    export class $CameraStandEntity extends $Entity implements $CameraHolder {
        destroy(dropItem: $Item_): void;
        canUse(player: $Player): boolean;
        release(): void;
        operator(): $CameraOperator;
        getClosestPlayerInRange(): ($Player) | undefined;
        isInInteractionRange(entity: $LivingEntity): boolean;
        openAttachmentsMenu(player: $Player, hand: $InteractionHand_): $InteractionResult;
        syncRotationToClients(): void;
        setCooldown(cooldown: number): void;
        getPlayerExecutingExposure(): ($Player) | undefined;
        getExposureAuthorEntity(): $Entity;
        getExposureCameraOperator(): ($CameraOperator) | undefined;
        getDamage(): number;
        isOnCooldown(): boolean;
        getCooldownPercent(): number;
        syncRotationToClientsIfNeeded(): void;
        setDamage(damage: number): void;
        getHurtDir(): number;
        playCameraRemoveSound(): void;
        getCamera(): $ItemStack;
        setCamera(cameraStack: $ItemStack_): void;
        playHitSound(): void;
        setHurtDir(hurtDir: number): void;
        isClientSide(): boolean;
        playBreakSound(): void;
        getHurtTime(): number;
        setHurtTime(hurtTime: number): void;
        playPlaceSound(): void;
        getCooldown(): number;
        startCooldown(cooldown: number): void;
        forceUpdate(): void;
        isCameraActive(): boolean;
        getOwnerPlayerUuid(): $UUID;
        getOwnerPlayer(): ($Player) | undefined;
        setOperator(operator: $CameraOperator): void;
        setCooldownTime(cooldown: number): void;
        getOperatorId(): number;
        setOwnerPlayer(player: $Player): void;
        stopControlling(): void;
        isInRangeForPhoto(player: $Player): boolean;
        getCooldownTime(): number;
        startControlling(player: $Player, cameraItem: $CameraItem): void;
        playCameraSetSound(): void;
        isMalfunctioned(): boolean;
        setMalfunctioned(malfunctioned: boolean): void;
        getPlayerAwardedForExposure(): ($Player) | undefined;
        asHolderEntity(): $Entity;
        getServerPlayerAwardedForExposure(): ($ServerPlayer) | undefined;
        getServerPlayerExecutingExposure(): ($ServerPlayer) | undefined;
        serializeNBT(arg0: $HolderLookup$Provider): $CompoundTag;
        xRot: number;
        hasImpulse: boolean;
        ars_Nouveau$motions: $Stack<any>;
        stuckSpeedMultiplier: $Vec3;
        tickCount: number;
        an_isRewinding: boolean;
        noPhysics: boolean;
        yo: number;
        static BOARDING_COOLDOWN: number;
        removalReason: $Entity$RemovalReason;
        yRotO: number;
        static CONTENTS_SLOT_INDEX: number;
        level: $Level;
        yRot: number;
        moveDist: number;
        static ID_TAG: string;
        mainSupportingBlockPos: ($BlockPos) | undefined;
        static DELTA_AFFECTED_BY_BLOCKS_BELOW_1_0: number;
        xRotO: number;
        zo: number;
        create_diesel_generators$turretPos: $BlockPos;
        walkDist: number;
        xOld: number;
        noCulling: boolean;
        wasInPowderSnow: boolean;
        hurtMarked: boolean;
        invulnerableTime: number;
        static UUID_TAG: string;
        static BASE_TICKS_REQUIRED_TO_FREEZE: number;
        fallDistance: number;
        portalProcess: $PortalProcessor;
        verticalCollision: boolean;
        static DELTA_AFFECTED_BY_BLOCKS_BELOW_0_5: number;
        static MAX_ENTITY_TAG_COUNT: number;
        static DELTA_AFFECTED_BY_BLOCKS_BELOW_0_2: number;
        verticalCollisionBelow: boolean;
        yOld: number;
        static DEFAULT_BB_WIDTH: number;
        eyeHeight: number;
        minorHorizontalCollision: boolean;
        static DEFAULT_BB_HEIGHT: number;
        walkDistO: number;
        static FREEZE_HURT_FREQUENCY: number;
        flyDist: number;
        isInPowderSnow: boolean;
        static ATTACHMENTS_NBT_KEY: string;
        static PASSENGERS_TAG: string;
        blocksBuilding: boolean;
        wasOnFire: boolean;
        zOld: number;
        static TOTAL_AIR_SUPPLY: number;
        xo: number;
        static BASE_SAFE_FALL_DISTANCE: number;
        wasTouchingWater: boolean;
        horizontalCollision: boolean;
        dimensions: $EntityDimensions;
        constructor(entityType: $EntityType_<$CameraStandEntity>, level: $Level_);
        get closestPlayerInRange(): ($Player) | undefined;
        get playerExecutingExposure(): ($Player) | undefined;
        get exposureAuthorEntity(): $Entity;
        get exposureCameraOperator(): ($CameraOperator) | undefined;
        get onCooldown(): boolean;
        get cooldownPercent(): number;
        get clientSide(): boolean;
        get cameraActive(): boolean;
        get ownerPlayerUuid(): $UUID;
        get operatorId(): number;
        get playerAwardedForExposure(): ($Player) | undefined;
        get serverPlayerAwardedForExposure(): ($ServerPlayer) | undefined;
        get serverPlayerExecutingExposure(): ($ServerPlayer) | undefined;
    }
}
