import { $LongList } from "@package/it/unimi/dsi/fastutil/longs";
import { $GlobalPos_ } from "@package/net/minecraft/core";
import { $IFluxDevice } from "@package/sonar/fluxnetworks/api/device";
import { $CompoundTag_ } from "@package/net/minecraft/nbt";
import { $FriendlyByteBuf } from "@package/net/minecraft/network";
import { $FluxDeviceConfigComponent_ } from "@package/sonar/fluxnetworks/common/data";
import { $AccessLevel, $NetworkMember, $SecurityLevel, $SecurityLevel_ } from "@package/sonar/fluxnetworks/api/network";
import { $Player } from "@package/net/minecraft/world/entity/player";
import { $UUID_, $UUID, $List, $Collection } from "@package/java/util";
import { $TileFluxDevice } from "@package/sonar/fluxnetworks/common/device";

declare module "@package/sonar/fluxnetworks/common/connection" {
    export class $NetworkStatistics {
        writeNBT(arg0: $CompoundTag_): void;
        readNBT(arg0: $CompoundTag_): void;
        getConnectionCount(): number;
        startProfiling(): void;
        stopProfiling(): void;
        fluxPointCount: number;
        energyInput: number;
        static CHANGE_COUNT: number;
        fluxPlugCount: number;
        energyOutput: number;
        totalEnergy: number;
        averageTickMicro: number;
        fluxControllerCount: number;
        fluxStorageCount: number;
        totalBuffer: number;
        energyChange: $LongList;
        constructor(arg0: $FluxNetwork);
        get connectionCount(): number;
    }
    export class $FluxNetwork {
        isValid(): boolean;
        getAllMembers(): $Collection<$NetworkMember>;
        getOwnerUUID(): $UUID;
        onDelete(): void;
        onEndServerTick(): void;
        getNetworkColor(): number;
        getNetworkID(): number;
        getNetworkName(): string;
        getPlayerAccess(arg0: $Player): $AccessLevel;
        canPlayerAccess(arg0: $Player, arg1: string): boolean;
        canPlayerAccess(arg0: $Player): boolean;
        getStatistics(): $NetworkStatistics;
        getSecurityLevel(): $SecurityLevel;
        enqueueConnectionAddition(arg0: $TileFluxDevice): boolean;
        enqueueConnectionRemoval(arg0: $TileFluxDevice, arg1: boolean): void;
        getConnectionByPos(arg0: $GlobalPos_): $IFluxDevice;
        readCustomTag(arg0: $CompoundTag_, arg1: number): void;
        writeCustomTag(arg0: $CompoundTag_, arg1: number): void;
        changeMembership(arg0: $Player, arg1: $UUID_, arg2: number): number;
        getMemberByUUID(arg0: $UUID_): $NetworkMember;
        setSecurityLevel(arg0: $SecurityLevel_): boolean;
        getAllConnections(): $Collection<$IFluxDevice>;
        setNetworkColor(arg0: number): boolean;
        getBufferLimiter(): number;
        setNetworkName(arg0: string): boolean;
        getLogicalDevices(arg0: number): $List<$TileFluxDevice>;
        static STORAGE: number;
        static OWNER_UUID: string;
        static NETWORK_COLOR: string;
        static MEMBERS: string;
        static MAX_NETWORK_NAME_LENGTH: number;
        static NETWORK_NAME: string;
        static PLUG: number;
        static CONNECTIONS: string;
        static INVALID: $FluxNetwork;
        static ANY: number;
        static SECURITY_LEVEL: string;
        static CONTROLLER: number;
        static POINT: number;
        static MAX_PASSWORD_LENGTH: number;
        get valid(): boolean;
        get allMembers(): $Collection<$NetworkMember>;
        get ownerUUID(): $UUID;
        get networkID(): number;
        get statistics(): $NetworkStatistics;
        get allConnections(): $Collection<$IFluxDevice>;
        get bufferLimiter(): number;
    }
    export class $TransferHandler {
        setPriority(arg0: number): boolean;
        getPriority(): number;
        getBuffer(): number;
        setLimit(arg0: number): void;
        getLimit(): number;
        getRequest(): number;
        readPacketBuffer(arg0: $FriendlyByteBuf, arg1: number): void;
        getChange(): number;
        writePacketBuffer(arg0: $FriendlyByteBuf, arg1: number): void;
        getRawPriority(): number;
        getSurgeMode(): boolean;
        getDisableLimit(): boolean;
        getRawLimit(): number;
        setSurgeMode(arg0: boolean): boolean;
        setDisableLimit(arg0: boolean): void;
        changeSettings(arg0: $CompoundTag_): boolean;
        readCustomTag(arg0: $CompoundTag_, arg1: number): void;
        applyConfiguration(arg0: $FluxDeviceConfigComponent_, arg1: number): void;
        writeCustomTag(arg0: $CompoundTag_, arg1: number): void;
        onNetworkChanged(): void;
        static PRI_GAIN_MAX: number;
        static PRI_USER_MIN: number;
        static STORAGE_PRI_DIFF: number;
        static PRI_GAIN_MIN: number;
        static PRI_USER_MAX: number;
        get buffer(): number;
        get request(): number;
        get change(): number;
        get rawPriority(): number;
        get rawLimit(): number;
    }
}
