import { $Color } from "@package/com/teamresourceful/resourcefullib/common/color";
import { $Function1_ } from "@package/kotlin/jvm/functions";
import { $Level, $Level_ } from "@package/net/minecraft/world/level";
import { $DefaultConstructorMarker } from "@package/kotlin/jvm/internal";
import { $Either } from "@package/com/mojang/datafixers/util";
import { $CompoundTag } from "@package/net/minecraft/nbt";
import { $MutableComponent, $Component } from "@package/net/minecraft/network/chat";
import { $TimedoorPlacementSettings } from "@package/earth/terrarium/tempad/api/sizing";
import { $EntityDimensions, $EntityType_, $Entity$RemovalReason, $PortalProcessor, $Entity } from "@package/net/minecraft/world/entity";
import { $Player } from "@package/net/minecraft/world/entity/player";
import { $UUID, $Stack, $UUID_ } from "@package/java/util";
import { $NamedGlobalVec3 } from "@package/earth/terrarium/tempad/api/locations";
import { $SyncableContext } from "@package/earth/terrarium/tempad/api/context";
import { $HolderLookup$Provider, $BlockPos } from "@package/net/minecraft/core";
import { $GameProfile } from "@package/com/mojang/authlib";
import { $ResourceLocation_, $ResourceKey_, $ResourceKey } from "@package/net/minecraft/resources";
import { $Object } from "@package/java/lang";
import { $Unit } from "@package/kotlin";
import { $Vec3_, $Vec3 } from "@package/net/minecraft/world/phys";
import { $BlockEntity } from "@package/net/minecraft/world/level/block/entity";

declare module "@package/earth/terrarium/tempad/common/entity" {
    export class $TimedoorEntity extends $Entity {
        getOwner(): $UUID;
        setOwner(arg0: $UUID_): void;
        setColor(arg0: $Color): void;
        getTargetAngle(): number;
        setLocation(arg0: $NamedGlobalVec3): void;
        getColor(): $Color;
        setOriginal(arg0: boolean): void;
        getOriginal(): boolean;
        setAnimationOffset(arg0: number): void;
        setTargetPos(arg0: $Vec3_): void;
        setClosingTime(arg0: number): void;
        getGlitching(): boolean;
        setBeganClosing(arg0: number): void;
        setTargetAngle(arg0: number): void;
        getTargetDimension(): $ResourceKey<$Level>;
        static access$getFail$cp(): $MutableComponent;
        getAnimationOffset(): number;
        getBeganClosing(): number;
        getClosingTime(): number;
        setTargetDimension(arg0: $ResourceKey_<$Level>): void;
        setLinkedPortalId(arg0: $UUID_): void;
        getLinkedPortalId(): $UUID;
        setSizing(arg0: $TimedoorPlacementSettings): void;
        getSizing(): $TimedoorPlacementSettings;
        getLinkedPortalEntity(): $TimedoorEntity;
        static access$getPosFail$cp(): $MutableComponent;
        static access$getEnteringFail$cp(): $MutableComponent;
        static access$getIntraDimFail$cp(): $MutableComponent;
        static access$getLeavingFail$cp(): $MutableComponent;
        static access$getInterDimFail$cp(): $MutableComponent;
        getTargetPos(): $Vec3;
        setGlitching(arg0: boolean): void;
        static access$tryInitReceivingPortal(arg0: $TimedoorEntity): void;
        static access$getIntraDimAllFail$cp(): $MutableComponent;
        static access$getNoChrononsFail$cp(): $MutableComponent;
        serializeNBT(arg0: $HolderLookup$Provider): $CompoundTag;
        xRot: number;
        hasImpulse: boolean;
        ars_Nouveau$motions: $Stack<any>;
        stuckSpeedMultiplier: $Vec3;
        tickCount: number;
        an_isRewinding: boolean;
        noPhysics: boolean;
        yo: number;
        static BOARDING_COOLDOWN: number;
        removalReason: $Entity$RemovalReason;
        yRotO: number;
        static CONTENTS_SLOT_INDEX: number;
        level: $Level;
        yRot: number;
        moveDist: number;
        static ID_TAG: string;
        mainSupportingBlockPos: ($BlockPos) | undefined;
        static DELTA_AFFECTED_BY_BLOCKS_BELOW_1_0: number;
        xRotO: number;
        zo: number;
        create_diesel_generators$turretPos: $BlockPos;
        walkDist: number;
        xOld: number;
        noCulling: boolean;
        wasInPowderSnow: boolean;
        hurtMarked: boolean;
        invulnerableTime: number;
        static UUID_TAG: string;
        static BASE_TICKS_REQUIRED_TO_FREEZE: number;
        fallDistance: number;
        portalProcess: $PortalProcessor;
        verticalCollision: boolean;
        static ANIMATION_LENGTH: number;
        static DELTA_AFFECTED_BY_BLOCKS_BELOW_0_5: number;
        static MAX_ENTITY_TAG_COUNT: number;
        static DELTA_AFFECTED_BY_BLOCKS_BELOW_0_2: number;
        verticalCollisionBelow: boolean;
        static Companion: $TimedoorEntity$Companion;
        yOld: number;
        static DEFAULT_BB_WIDTH: number;
        eyeHeight: number;
        minorHorizontalCollision: boolean;
        static DEFAULT_BB_HEIGHT: number;
        walkDistO: number;
        static FREEZE_HURT_FREQUENCY: number;
        flyDist: number;
        isInPowderSnow: boolean;
        static ATTACHMENTS_NBT_KEY: string;
        static IDLE_BEFORE_START: number;
        static PASSENGERS_TAG: string;
        blocksBuilding: boolean;
        wasOnFire: boolean;
        zOld: number;
        static TOTAL_AIR_SUPPLY: number;
        xo: number;
        static BASE_SAFE_FALL_DISTANCE: number;
        wasTouchingWater: boolean;
        horizontalCollision: boolean;
        dimensions: $EntityDimensions;
        constructor(arg0: $EntityType_<never>, arg1: $Level_);
        set location(value: $NamedGlobalVec3);
        get linkedPortalEntity(): $TimedoorEntity;
    }
    export class $TimedoorEntity$Companion {
        getFail(): $MutableComponent;
        getPosFail(): $MutableComponent;
        openTimedoor(arg0: $Player, arg1: $SyncableContext<never>, arg2: $ResourceLocation_, arg3: $UUID_, arg4: $NamedGlobalVec3, arg5: $Function1_<$TimedoorEntity, $Unit>): $Component;
        openTimedoor(arg0: $GameProfile, arg1: $BlockEntity, arg2: $ResourceLocation_, arg3: $UUID_, arg4: $NamedGlobalVec3, arg5: $TimedoorPlacementSettings, arg6: $Function1_<$TimedoorEntity, $Unit>): $Component;
        getTimedoor(arg0: $Level_, arg1: $NamedGlobalVec3, arg2: boolean): $Either<$TimedoorEntity, $Component>;
        static openTimedoor$default(arg0: $TimedoorEntity$Companion, arg1: $Player, arg2: $SyncableContext<any>, arg3: $ResourceLocation_, arg4: $UUID_, arg5: $NamedGlobalVec3, arg6: $Function1_<any, any>, arg7: number, arg8: $Object): $Component;
        static openTimedoor$default(arg0: $TimedoorEntity$Companion, arg1: $GameProfile, arg2: $BlockEntity, arg3: $ResourceLocation_, arg4: $UUID_, arg5: $NamedGlobalVec3, arg6: $TimedoorPlacementSettings, arg7: $Function1_<any, any>, arg8: number, arg9: $Object): $Component;
        getLeavingFail(): $MutableComponent;
        getEnteringFail(): $MutableComponent;
        getNoChrononsFail(): $MutableComponent;
        getInterDimFail(): $MutableComponent;
        getIntraDimFail(): $MutableComponent;
        getIntraDimAllFail(): $MutableComponent;
        static getTimedoor$default(arg0: $TimedoorEntity$Companion, arg1: $Level_, arg2: $NamedGlobalVec3, arg3: boolean, arg4: number, arg5: $Object): $Either<any, any>;
        constructor(arg0: $DefaultConstructorMarker);
        get fail(): $MutableComponent;
        get posFail(): $MutableComponent;
        get leavingFail(): $MutableComponent;
        get enteringFail(): $MutableComponent;
        get noChrononsFail(): $MutableComponent;
        get interDimFail(): $MutableComponent;
        get intraDimFail(): $MutableComponent;
        get intraDimAllFail(): $MutableComponent;
    }
}
