import { $Level } from "@package/net/minecraft/world/level";
import { $LightGraveData } from "@package/com/b1n_ry/yigd/networking";
import { $MinecraftServer } from "@package/net/minecraft/server";
import { $ItemStack_, $ItemStack } from "@package/net/minecraft/world/item";
import { $CompoundTag, $CompoundTag_ } from "@package/net/minecraft/nbt";
import { $DeathContext_, $GraveyardData, $GraveStatus, $DirectionalPos, $TimePoint, $GraveItem, $GraveStatus_ } from "@package/com/b1n_ry/yigd/data";
import { $ResolvableProfile_, $ResolvableProfile } from "@package/net/minecraft/world/item/component";
import { $Component_, $Component } from "@package/net/minecraft/network/chat";
import { $UUID, $UUID_ } from "@package/java/util";
import { $Predicate_, $Function_ } from "@package/java/util/function";
import { $InteractionResult } from "@package/net/minecraft/world";
import { $HolderLookup$Provider, $BlockPos, $BlockPos_, $Direction_, $NonNullList } from "@package/net/minecraft/core";
import { $ServerPlayer, $ServerLevel } from "@package/net/minecraft/server/level";
import { $DropRule, $GraveItemModificationConsumer_ } from "@package/com/b1n_ry/yigd/util";
import { $BlockState_ } from "@package/net/minecraft/world/level/block/state";
import { $ResourceKey_, $ResourceKey } from "@package/net/minecraft/resources";
import { $Vec3_ } from "@package/net/minecraft/world/phys";

declare module "@package/com/b1n_ry/yigd/components" {
    export class $RespawnComponent {
        isEmpty(): boolean;
        apply(arg0: $ServerPlayer): void;
        static fromNbt(arg0: $CompoundTag_, arg1: $HolderLookup$Provider): $RespawnComponent;
        toNbt(arg0: $HolderLookup$Provider): $CompoundTag;
        setSoulboundInventory(arg0: $InventoryComponent): void;
        setGraveGenerated(arg0: boolean): void;
        setSoulboundExp(arg0: $ExpComponent): void;
        primeForRespawn(arg0: $ResolvableProfile_): void;
        getSoulboundExp(): $ExpComponent;
        wasGraveGenerated(): boolean;
        constructor(arg0: $ServerPlayer);
        get empty(): boolean;
        set soulboundInventory(value: $InventoryComponent);
        set graveGenerated(value: boolean);
    }
    export class $GraveComponent {
        isEmpty(): boolean;
        getOwner(): $ResolvableProfile;
        isLocked(): boolean;
        getCreationTime(): $TimePoint;
        getWorld(): $ServerLevel;
        getPos(): $BlockPos;
        claim(arg0: $ServerPlayer, arg1: $ServerLevel, arg2: $BlockState_, arg3: $BlockPos_, arg4: $ItemStack_): $InteractionResult;
        getStatus(): $GraveStatus;
        getDeathMessage(): $Component;
        setWorld(arg0: $ServerLevel): void;
        setStatus(arg0: $GraveStatus_): void;
        static fromNbt(arg0: $CompoundTag_, arg1: $HolderLookup$Provider, arg2: $MinecraftServer): $GraveComponent;
        toNbt(arg0: $HolderLookup$Provider): $CompoundTag;
        setPos(arg0: $BlockPos_): void;
        onDestroyed(): void;
        setLocked(arg0: boolean): void;
        backUp(): void;
        toLightData(): $LightGraveData;
        placeAndLoad(arg0: $Direction_, arg1: $DeathContext_, arg2: $BlockPos_, arg3: $ServerLevel, arg4: $RespawnComponent): void;
        generateOrDrop(arg0: $Direction_, arg1: $DeathContext_, arg2: $RespawnComponent): void;
        tryPlaceGrave(arg0: $BlockState_): boolean;
        getExpComponent(): $ExpComponent;
        getKillerId(): $UUID;
        removeGraveBlock(): boolean;
        hasExistedTicks(arg0: number): boolean;
        findGravePos(arg0: $Direction_): $DirectionalPos;
        applyToPlayer(arg0: $ServerPlayer, arg1: $ServerLevel, arg2: $Vec3_, arg3: boolean): void;
        applyToPlayer(arg0: $ServerPlayer, arg1: $ServerLevel, arg2: $Vec3_, arg3: boolean, arg4: $Predicate_<$DropRule>): void;
        setExpComponent(arg0: $ExpComponent): void;
        isGraveEmpty(): boolean;
        getTimeUntilRobbable(): string;
        getInventoryComponent(): $InventoryComponent;
        setInventoryComponent(arg0: $InventoryComponent): void;
        getWorldRegistryKey(): $ResourceKey<$Level>;
        dropAllGraveItems(): void;
        replaceWithOld(arg0: $BlockState_, arg1: boolean): boolean;
        getGraveId(): $UUID;
        static graveyardData: $GraveyardData;
        constructor(arg0: $ResolvableProfile_, arg1: $InventoryComponent, arg2: $ExpComponent, arg3: $ResourceKey_<$Level>, arg4: $BlockPos_, arg5: $Component_, arg6: $UUID_, arg7: $GraveStatus_, arg8: boolean, arg9: $TimePoint, arg10: $UUID_);
        constructor(arg0: $ResolvableProfile_, arg1: $InventoryComponent, arg2: $ExpComponent, arg3: $ServerLevel, arg4: $BlockPos_, arg5: $Component_, arg6: $UUID_, arg7: $GraveStatus_, arg8: boolean, arg9: $TimePoint, arg10: $UUID_);
        constructor(arg0: $ResolvableProfile_, arg1: $InventoryComponent, arg2: $ExpComponent, arg3: $ServerLevel, arg4: $Vec3_, arg5: $Component_, arg6: $UUID_);
        get empty(): boolean;
        get owner(): $ResolvableProfile;
        get creationTime(): $TimePoint;
        get deathMessage(): $Component;
        get killerId(): $UUID;
        get graveEmpty(): boolean;
        get timeUntilRobbable(): string;
        get worldRegistryKey(): $ResourceKey<$Level>;
        get graveId(): $UUID;
    }
    export class $InventoryComponent {
        clear(): void;
        isEmpty(): boolean;
        merge(arg0: $InventoryComponent, arg1: $ServerPlayer): $NonNullList<$ItemStack>;
        containsAny(arg0: $Predicate_<$ItemStack>, arg1: $Predicate_<string>, arg2: $Predicate_<number>): boolean;
        static clearPlayer(arg0: $ServerPlayer): void;
        removeItem(arg0: $Predicate_<$ItemStack>, arg1: number): boolean;
        dropAll(arg0: $ServerLevel, arg1: $Vec3_): void;
        getItems(): $NonNullList<$GraveItem>;
        static fromNbt(arg0: $CompoundTag_, arg1: $HolderLookup$Provider): $InventoryComponent;
        toNbt(arg0: $HolderLookup$Provider): $CompoundTag;
        handleGraveItems(arg0: $Predicate_<string>, arg1: $GraveItemModificationConsumer_): void;
        applyLoss(): void;
        graveSize(): number;
        dropGraveItems(arg0: $ServerLevel, arg1: $Vec3_): void;
        filteredInv(arg0: $Predicate_<$DropRule>): $InventoryComponent;
        applyToPlayer(arg0: $ServerPlayer): $NonNullList<$ItemStack>;
        isGraveEmpty(): boolean;
        pullBindingCurseItems(arg0: $ServerPlayer): $NonNullList<$ItemStack>;
        static dropItemIfToBeDropped(arg0: $ItemStack_, arg1: number, arg2: number, arg3: number, arg4: $ServerLevel): void;
        static listFromNbt<T>(arg0: $CompoundTag_, arg1: $Function_<$CompoundTag, T>, arg2: T, arg3: string, arg4: string): $NonNullList<T>;
        static listFromNbt<T>(arg0: $CompoundTag_, arg1: $Function_<$CompoundTag, T>, arg2: T): $NonNullList<T>;
        onDeath(arg0: $DeathContext_): void;
        static listToNbt<T>(arg0: $NonNullList<T>, arg1: $Function_<T, $CompoundTag>, arg2: $Predicate_<T>, arg3: string, arg4: string): $CompoundTag;
        static listToNbt<T>(arg0: $NonNullList<T>, arg1: $Function_<T, $CompoundTag>, arg2: $Predicate_<T>): $CompoundTag;
        getAllExtraItems(arg0: boolean): $NonNullList<$ItemStack>;
        mergeSingleItem(arg0: $GraveItem, arg1: boolean): void;
        mergeKeepDropRules(arg0: $InventoryComponent, arg1: $ServerPlayer): $NonNullList<$GraveItem>;
        addExtraGraveItem(arg0: $GraveItem): void;
        offHandSize: number;
        armorSize: number;
        mainSize: number;
        static EMPTY_GRAVE_ITEM: $GraveItem;
        constructor(arg0: $ServerPlayer);
        get empty(): boolean;
        get items(): $NonNullList<$GraveItem>;
        get graveEmpty(): boolean;
    }
    export class $ExpComponent {
        clear(): void;
        isEmpty(): boolean;
        copy(): $ExpComponent;
        dropAll(arg0: $ServerLevel, arg1: $Vec3_): void;
        static fromNbt(arg0: $CompoundTag_): $ExpComponent;
        toNbt(): $CompoundTag;
        applyToPlayer(arg0: $ServerPlayer): void;
        getStoredXp(): number;
        getSoulboundExp(): $ExpComponent;
        getXpLevel(): number;
        static xpToLevels(arg0: number): number;
        static clearXp(arg0: $ServerPlayer): void;
        getOriginalXp(): number;
        setStoredXp(arg0: number): void;
        getXpDropAmount(arg0: $ServerPlayer): number;
        constructor(arg0: $ServerPlayer);
        get empty(): boolean;
        get soulboundExp(): $ExpComponent;
        get xpLevel(): number;
        get originalXp(): number;
    }
}
