import { $LongSet } from "@package/it/unimi/dsi/fastutil/longs";
import { $TranslationManager, $TranslationKey_ } from "@package/dev/ftb/mods/ftbquests/quest/translation";
import { $Codec } from "@package/com/mojang/serialization";
import { $Tag_, $CompoundTag, $CompoundTag_ } from "@package/net/minecraft/nbt";
import { $Pair } from "@package/com/mojang/datafixers/util";
import { $Entity } from "@package/net/minecraft/world/entity";
import { $UUID, $List, $UUID_, $Date, $List_, $Collection, $Comparator, $Map, $Set } from "@package/java/util";
import { $WeakReference } from "@package/java/lang/ref";
import { $RandomSource } from "@package/net/minecraft/util";
import { $RewardTable, $EntityWeight, $LootCrate } from "@package/dev/ftb/mods/ftbquests/quest/loot";
import { $Predicate, $Supplier_, $Consumer_, $Predicate_ } from "@package/java/util/function";
import { $ChatFormatting } from "@package/net/minecraft";
import { $ServerPlayer } from "@package/net/minecraft/server/level";
import { $HolderLookup$Provider } from "@package/net/minecraft/core";
import { $Path, $Path_ } from "@package/java/nio/file";
import { $RegistryFriendlyByteBuf, $FriendlyByteBuf } from "@package/net/minecraft/network";
import { $Color4I, $ImageIcon, $Icon } from "@package/dev/ftb/mods/ftblibrary/icon";
import { $Enum, $Class, $Runnable_, $Comparable, $Object } from "@package/java/lang";
import { $SNBTCompoundTag } from "@package/dev/ftb/mods/ftblibrary/snbt";
import { $ItemStack_, $ItemStack } from "@package/net/minecraft/world/item";
import { $MutableComponent, $Component } from "@package/net/minecraft/network/chat";
import { $Team } from "@package/dev/ftb/mods/ftbteams/api";
import { $PixelBuffer } from "@package/dev/ftb/mods/ftblibrary/math";
import { $RecipeModHelper$Components } from "@package/dev/ftb/mods/ftbquests/integration";
import { $QuestFile } from "@package/dev/ftb/mods/ftbquests/api";
import { $TooltipList } from "@package/dev/ftb/mods/ftblibrary/util";
import { $Player } from "@package/net/minecraft/world/entity/player";
import { $QuestProgressEventData } from "@package/dev/ftb/mods/ftbquests/events";
import { $Env } from "@package/dev/architectury/utils";
import { $CommandSourceStack } from "@package/net/minecraft/commands";
import { $NameMap, $ConfigGroup, $Tristate } from "@package/dev/ftb/mods/ftblibrary/config";
import { $Stream } from "@package/java/util/stream";
import { $ProgressChange } from "@package/dev/ftb/mods/ftbquests/util";
import { $TaskType, $Task } from "@package/dev/ftb/mods/ftbquests/quest/task";
import { $GuiGraphics } from "@package/net/minecraft/client/gui";
import { $RewardType, $Reward, $RewardAutoClaim, $RewardClaimType } from "@package/dev/ftb/mods/ftbquests/quest/reward";
import { $StreamCodec } from "@package/net/minecraft/network/codec";
export * as reward from "@package/dev/ftb/mods/ftbquests/quest/reward";
export * as task from "@package/dev/ftb/mods/ftbquests/quest/task";
export * as translation from "@package/dev/ftb/mods/ftbquests/quest/translation";
export * as loot from "@package/dev/ftb/mods/ftbquests/quest/loot";

declare module "@package/dev/ftb/mods/ftbquests/quest" {
    export class $QuestObject extends $QuestObjectBase {
        getChildren(): $Collection<$QuestObject>;
        onCompleted(data: $QuestProgressEventData<never>): void;
        isVisible(data: $TeamData): boolean;
        onStarted(data: $QuestProgressEventData<never>): void;
        isOptionalForProgression(teamData: $TeamData): boolean;
        hasUnclaimedRewardsRaw(teamData: $TeamData, player: $UUID_): boolean;
        getProgressColor(data: $TeamData): $Color4I;
        getProgressColor(data: $TeamData, dim: boolean): $Color4I;
        isSearchable(data: $TeamData): boolean;
        isCompletedRaw(data: $TeamData): boolean;
        getRelatedQuest(): $Quest;
        cacheProgress(): boolean;
        getRelativeProgressFromChildren(arg0: $TeamData): number;
        static getRelativeProgressFromChildren(progressSum: number, count: number): number;
        id: number;
        constructor(id: number);
        get children(): $Collection<$QuestObject>;
        get relatedQuest(): $Quest;
    }
    export class $Quest extends $QuestObject implements $Movable, $Excludable {
        getSize(): number;
        setSize(size: number): void;
        getShape(): string;
        getWidth(): number;
        getHeight(): number;
        getDescription(): $List<$Component>;
        getX(): number;
        getMinWidth(): number;
        onMoved(newX: number, newY: number, newChapterId: number): void;
        getY(): number;
        setY(y: number): void;
        setX(x: number): void;
        addDependency(object: $QuestObject): void;
        getTasks(): $Collection<$Task>;
        addReward(reward: $Reward): void;
        isOptional(): boolean;
        addTask(task: $Task): void;
        getSubtitle(): $Component;
        copyToClipboard(): void;
        getRewards(): $Collection<$Reward>;
        removeTask(task: $Task): void;
        getChapter(): $Chapter;
        hideDetailsUntilStartable(): boolean;
        ignoreRewardBlocking(): boolean;
        getMinRequiredDependencies(): number;
        areDependenciesVisible(teamData: $TeamData): boolean;
        buildDescriptionIndex(): $List<$Pair<number, number>>;
        isQuestObjectExcluded(teamData: $TeamData): boolean;
        shouldHideDependencyLines(): boolean;
        getHideTextUntilComplete(): $Tristate;
        shouldHideDependentLines(): boolean;
        getRequireSequentialTasks(): boolean;
        initiateMoveClientSide(to: $Chapter, x: number, y: number): void;
        resetProgressIfRepeatable(data: $TeamData, player: $UUID_): boolean;
        writeRewards(tag: $CompoundTag_, provider: $HolderLookup$Provider): void;
        verifyDependencies(autofix: boolean): boolean;
        getProgressionMode(): $ProgressionMode;
        removeDependency(object: $QuestObject): void;
        moveRewardLeft(reward: $Reward): void;
        shouldHideLockIcon(): boolean;
        getGuidePage(): string;
        setTaskList(tasks: $List_<$Task>): void;
        hasDependency(object: $QuestObject): boolean;
        moveTaskRight(task: $Task): void;
        setRewardList(rewards: $List_<$Reward>): void;
        moveTaskLeft(task: $Task): void;
        getRawSubtitle(): string;
        moveRewardRight(reward: $Reward): void;
        streamDependencies(): $Stream<$QuestObject>;
        removeReward(reward: $Reward): void;
        setRawSubtitle(rawSubtitle: string): void;
        getRawDescription(): $List<string>;
        hasDependencies(): boolean;
        getDependants(): $Collection<$QuestObject>;
        canBeRepeated(): boolean;
        setRawDescription(rawDescription: $List_<string>): void;
        getIconScale(): number;
        showInRecipeMod(): boolean;
        clearDependencies(): void;
        getTasksAsList(): $List<$Task>;
        getMovableID(): number;
        allTasksCompleted(teamData: $TeamData): boolean;
        getRepeatCooldown(): number;
        isExclusiveQuest(): boolean;
        writeTasks(tag: $CompoundTag_, provider: $HolderLookup$Provider): void;
        removeInvalidDependencies(): void;
        areDependenciesComplete(teamData: $TeamData): boolean;
        getRotation(): number;
        isAlignToCorner(): boolean;
        drawMoved(graphics: $GuiGraphics): void;
        id: number;
        static PAGEBREAK_CODE: string;
        constructor(id: number, chapter: $Chapter);
        get shape(): string;
        get width(): number;
        get height(): number;
        get description(): $List<$Component>;
        get minWidth(): number;
        get tasks(): $Collection<$Task>;
        get optional(): boolean;
        get subtitle(): $Component;
        get rewards(): $Collection<$Reward>;
        get chapter(): $Chapter;
        get minRequiredDependencies(): number;
        get hideTextUntilComplete(): $Tristate;
        get requireSequentialTasks(): boolean;
        get progressionMode(): $ProgressionMode;
        get guidePage(): string;
        set taskList(value: $List_<$Task>);
        set rewardList(value: $List_<$Reward>);
        get dependants(): $Collection<$QuestObject>;
        get iconScale(): number;
        get tasksAsList(): $List<$Task>;
        get movableID(): number;
        get repeatCooldown(): number;
        get exclusiveQuest(): boolean;
        get rotation(): number;
        get alignToCorner(): boolean;
    }
    export class $DefaultChapterGroup extends $ChapterGroup {
        id: number;
        constructor(f: $BaseQuestFile);
    }
    export class $ChapterImage implements $Movable {
        copy(newChapter: $Chapter, newX: number, newY: number): $ChapterImage;
        getShape(): string;
        getWidth(): number;
        getHeight(): number;
        getImage(): $Icon;
        getX(): number;
        getColor(): $Color4I;
        getTitle(): $Component;
        onMoved(x: number, y: number, chapterId: number): void;
        getOrder(): number;
        getY(): number;
        getClick(): string;
        writeData(nbt: $CompoundTag_): $CompoundTag;
        getRotation(): number;
        setPosition(x: number, y: number): $ChapterImage;
        getAlpha(): number;
        readData(nbt: $CompoundTag_): void;
        setImage(image: $Icon): $ChapterImage;
        copyToClipboard(): void;
        getChapter(): $Chapter;
        initiateMoveClientSide(to: $Chapter, _x: number, _y: number): void;
        isAlignToCorner(): boolean;
        fillConfigGroup(config: $ConfigGroup): void;
        readNetData(buffer: $FriendlyByteBuf): void;
        writeNetData(buffer: $FriendlyByteBuf): void;
        static fromNet(parent: $Chapter, buf: $FriendlyByteBuf): $ChapterImage;
        getMovableID(): number;
        shouldShowImage(teamData: $TeamData): boolean;
        static isImageInClipboard(): boolean;
        addHoverText(list: $TooltipList): void;
        fixupAspectRatio(adjustWidth: boolean): void;
        isAspectRatioOff(): boolean;
        drawMoved(graphics: $GuiGraphics): void;
        static FTBQ_IMAGE: string;
        static clipboard: $WeakReference<$ChapterImage>;
        static STREAM_CODEC: $StreamCodec<$FriendlyByteBuf, $ChapterImage>;
        constructor(c: $Chapter);
        get shape(): string;
        get width(): number;
        get height(): number;
        get x(): number;
        get color(): $Color4I;
        get title(): $Component;
        get order(): number;
        get y(): number;
        get click(): string;
        get rotation(): number;
        get alpha(): number;
        get chapter(): $Chapter;
        get alignToCorner(): boolean;
        get movableID(): number;
        static get imageInClipboard(): boolean;
        get aspectRatioOff(): boolean;
    }
    export class $Excludable {
    }
    export interface $Excludable {
        getId(): number;
        isQuestObjectExcluded(arg0: $TeamData): boolean;
        get id(): number;
    }
    export class $QuestLink extends $QuestObject implements $Movable, $Excludable {
        getShape(): string;
        getWidth(): number;
        getHeight(): number;
        linksTo(quest: $Quest): boolean;
        getX(): number;
        onMoved(newX: number, newY: number, newChapterId: number): void;
        getY(): number;
        setPosition(qx: number, qy: number): void;
        copyToClipboard(): void;
        getQuest(): ($Quest) | undefined;
        getChapter(): $Chapter;
        isQuestObjectExcluded(teamData: $TeamData): boolean;
        initiateMoveClientSide(to: $Chapter, x: number, y: number): void;
        getMovableID(): number;
        getRotation(): number;
        isAlignToCorner(): boolean;
        drawMoved(graphics: $GuiGraphics): void;
        id: number;
        constructor(id: number, chapter: $Chapter, linkId: number);
        get shape(): string;
        get width(): number;
        get height(): number;
        get x(): number;
        get y(): number;
        get quest(): ($Quest) | undefined;
        get chapter(): $Chapter;
        get movableID(): number;
        get rotation(): number;
        get alignToCorner(): boolean;
    }
    export class $Movable {
    }
    export interface $Movable {
        getShape(): string;
        getWidth(): number;
        getHeight(): number;
        getX(): number;
        getTitle(): $Component;
        onMoved(arg0: number, arg1: number, arg2: number): void;
        getY(): number;
        getRotation(): number;
        copyToClipboard(): void;
        getChapter(): $Chapter;
        initiateMoveClientSide(arg0: $Chapter, arg1: number, arg2: number): void;
        isAlignToCorner(): boolean;
        getMovableID(): number;
        drawMoved(graphics: $GuiGraphics): void;
        get shape(): string;
        get width(): number;
        get height(): number;
        get x(): number;
        get title(): $Component;
        get y(): number;
        get rotation(): number;
        get chapter(): $Chapter;
        get alignToCorner(): boolean;
        get movableID(): number;
    }
    export class $QuestObjectType extends $Enum<$QuestObjectType> implements $Predicate<$QuestObjectBase> {
        static values(): $QuestObjectType[];
        test(object: $QuestObjectBase): boolean;
        static valueOf(name: string): $QuestObjectType;
        getId(): string;
        getColor(): $ChatFormatting;
        getCompletedMessage(): $Component;
        or(arg0: $Predicate_<$QuestObjectBase>): $Predicate<$QuestObjectBase>;
        negate(): $Predicate<$QuestObjectBase>;
        and(arg0: $Predicate_<$QuestObjectBase>): $Predicate<$QuestObjectBase>;
        static TASK: $QuestObjectType;
        static ALL_PROGRESSING_OR_NULL: $Predicate<$QuestObjectBase>;
        static NULL: $QuestObjectType;
        static NAME_MAP: $NameMap<$QuestObjectType>;
        static REWARD: $QuestObjectType;
        static STREAM_CODEC: $StreamCodec<$FriendlyByteBuf, $QuestObjectType>;
        static ALL_PROGRESSING: $Predicate<$QuestObjectBase>;
        static CHAPTER: $QuestObjectType;
        static QUEST_LINK: $QuestObjectType;
        static CHAPTER_GROUP: $QuestObjectType;
        static FILE: $QuestObjectType;
        static REWARD_TABLE: $QuestObjectType;
        static QUEST: $QuestObjectType;
        get id(): string;
        get color(): $ChatFormatting;
        get completedMessage(): $Component;
    }
    /**
     * Values that may be interpreted as {@link $QuestObjectType}.
     */
    export type $QuestObjectType_ = "null" | "file" | "chapter" | "quest" | "task" | "reward" | "reward_table" | "chapter_group" | "quest_link";
    export class $BaseQuestFile extends $QuestObject implements $QuestFile {
        remove(id: number): $QuestObjectBase;
        get(id: number): $QuestObject;
        collect<T extends $QuestObjectBase>(cls: $Class<T>, filter: $Predicate_<T>): $List<T>;
        collect<T extends $QuestObjectBase>(clazz: $Class<T>): $List<T>;
        create(id: number, type: $QuestObjectType_, parent: number, extra: $CompoundTag_): $QuestObjectBase;
        getID(obj: $Object): number;
        getBase(id: number): $QuestObjectBase;
        getLocale(): string;
        getFallbackLocale(): string;
        isLoading(): boolean;
        getTask(id: number): $Task;
        getSide(): $Env;
        newID(): number;
        addData(data: $TeamData, override: boolean): void;
        makeRandomLootCrate(entity: $Entity, random: $RandomSource): ($LootCrate) | undefined;
        dropBookOnDeath(): boolean;
        isDropLootCrates(): boolean;
        deleteObject(arg0: number): void;
        canEdit(): boolean;
        markDirty(): void;
        getReward(id: number): $Reward;
        getFolder(): $Path;
        isServerSide(): boolean;
        getQuest(id: number): $Quest;
        getChapter(id: number): $Chapter;
        getTeamData(player: $Player): ($TeamData) | undefined;
        updateLootCrates(): void;
        getAltTitle(): $MutableComponent;
        getAllObjects(): $Collection<$QuestObjectBase>;
        writeNetDataFull(buffer: $RegistryFriendlyByteBuf): void;
        writeDataFull(folder: $Path_, provider: $HolderLookup$Provider): void;
        readDataFull(folder: $Path_, provider: $HolderLookup$Provider): void;
        readNetDataFull(buffer: $RegistryFriendlyByteBuf): void;
        getAllTeamData(): $Collection<$TeamData>;
        removeRewardTable(rewardTable: $RewardTable): void;
        moveChapterGroup(id: number, movingUp: boolean): boolean;
        getSubmitTasks(): $List<$Task>;
        getLootCrateNoDrop(): $EntityWeight;
        getProgressionMode(): $ProgressionMode;
        getGridScale(): number;
        getDetectionDelay(): number;
        getRewardTables(): $List<$RewardTable>;
        isDisableGui(): boolean;
        getCraftingTasks(): $List<$Task>;
        isPlayerOnTeam(arg0: $Player, arg1: $TeamData): boolean;
        forAllQuestLinks(consumer: $Consumer_<$QuestLink>): void;
        addRewardTable(rewardTable: $RewardTable): void;
        getAllChapters(): $List<$Chapter>;
        getEmergencyItems(): $List<$ItemStack>;
        getVisibleChapters(data: $TeamData): $List<$Chapter>;
        getAllTasks(): $List<$Task>;
        getRewardType(typeId: number): $RewardType;
        getChapterGroups(): $List<$ChapterGroup>;
        isPauseGame(): boolean;
        getTaskType(typeId: number): $TaskType;
        getRewardTable(id: number): $RewardTable;
        getChapterGroup(id: number): $ChapterGroup;
        getChapterOrThrow(id: number): $Chapter;
        forAllQuests(consumer: $Consumer_<$Quest>): void;
        getLootCrate(id: string): $LootCrate;
        refreshIDMap(): void;
        forAllChapters(consumer: $Consumer_<$Chapter>): void;
        showLockIcons(): boolean;
        refreshGui(): void;
        readID(tag: $Tag_): number;
        readID(id: number): number;
        getQuestObjectOrThrow<T extends $QuestObjectBase>(id: number, cls: $Class<T>): T;
        getTranslationManager(): $TranslationManager;
        isDefaultTeamConsumeItems(): boolean;
        isDefaultPerTeamReward(): boolean;
        isDefaultQuestDisableJEI(): boolean;
        clearCachedProgress(): void;
        removeEmptyRewardTables(source: $CommandSourceStack): number;
        forAllChapterGroups(consumer: $Consumer_<$ChapterGroup>): void;
        getDefaultQuestShape(): string;
        getDefaultChapterGroup(): $DefaultChapterGroup;
        getEmergencyItemsCooldown(): number;
        getOrCreateTeamData(team: $Team): $TeamData;
        getOrCreateTeamData(teamId: $UUID_): $TeamData;
        getOrCreateTeamData(player: $Entity): $TeamData;
        getNullableTeamData(id: $UUID_): $TeamData;
        isHideExcludedQuests(): boolean;
        getFirstVisibleChapter(data: $TeamData): $Chapter;
        getDefaultRewardAutoClaim(): $RewardAutoClaim;
        refreshRewardTableRewardIDs(): void;
        static VERSION: number;
        id: number;
        static STREAM_CODEC: $StreamCodec<$RegistryFriendlyByteBuf, $BaseQuestFile>;
        constructor();
        get locale(): string;
        get fallbackLocale(): string;
        get loading(): boolean;
        get side(): $Env;
        get dropLootCrates(): boolean;
        get folder(): $Path;
        get serverSide(): boolean;
        get altTitle(): $MutableComponent;
        get allObjects(): $Collection<$QuestObjectBase>;
        get allTeamData(): $Collection<$TeamData>;
        get submitTasks(): $List<$Task>;
        get lootCrateNoDrop(): $EntityWeight;
        get progressionMode(): $ProgressionMode;
        get gridScale(): number;
        get detectionDelay(): number;
        get rewardTables(): $List<$RewardTable>;
        get disableGui(): boolean;
        get craftingTasks(): $List<$Task>;
        get allChapters(): $List<$Chapter>;
        get emergencyItems(): $List<$ItemStack>;
        get allTasks(): $List<$Task>;
        get chapterGroups(): $List<$ChapterGroup>;
        get pauseGame(): boolean;
        get translationManager(): $TranslationManager;
        get defaultTeamConsumeItems(): boolean;
        get defaultPerTeamReward(): boolean;
        get defaultQuestDisableJEI(): boolean;
        get defaultQuestShape(): string;
        get defaultChapterGroup(): $DefaultChapterGroup;
        get emergencyItemsCooldown(): number;
        get hideExcludedQuests(): boolean;
        get defaultRewardAutoClaim(): $RewardAutoClaim;
    }
    export class $QuestShape extends $Icon {
        static get(id: string): $QuestShape;
        static map(): $Map<string, $QuestShape>;
        static reload(list: $List_<string>): void;
        getShape(): $ImageIcon;
        getBackground(): $ImageIcon;
        getOutline(): $ImageIcon;
        shouldDraw(): boolean;
        getShapePixels(): $PixelBuffer;
        static CODEC: $Codec<$Icon>;
        static idMapWithDefault: $NameMap<string>;
        static idMap: $NameMap<string>;
        static STRING_CODEC: $Codec<$Icon>;
        static STREAM_CODEC: $StreamCodec<$FriendlyByteBuf, $Icon>;
        constructor(id: string);
        get shape(): $ImageIcon;
        get background(): $ImageIcon;
        get outline(): $ImageIcon;
        get shapePixels(): $PixelBuffer;
    }
    export class $Chapter extends $QuestObject {
        getIndex(): number;
        getFilename(): string;
        getGroup(): $ChapterGroup;
        getImages(): $List<$ChapterImage>;
        hideQuestDetailsUntilStartable(): boolean;
        isHideQuestUntilDepsVisible(): boolean;
        getDefaultQuestSize(): number;
        isDefaultRepeatable(): boolean;
        hideQuestUntilDepsComplete(): boolean;
        isRequireSequentialTasks(): boolean;
        addQuestLink(link: $QuestLink): void;
        getAltTitle(): $MutableComponent;
        getQuestLinks(): $List<$QuestLink>;
        getProgressionMode(): $ProgressionMode;
        getRawSubtitle(): $List<string>;
        setRawSubtitle(rawSubtitle: $List_<string>): void;
        removeQuest(quest: $Quest): void;
        getQuests(): $List<$Quest>;
        addQuest(quest: $Quest): void;
        consumeItems(): boolean;
        isAutofocus(id: number): boolean;
        getDefaultMinWidth(): number;
        removeQuestLink(link: $QuestLink): void;
        removeImage(image: $ChapterImage): void;
        getAutofocus(): ($Movable) | undefined;
        setAutofocus(id: number): void;
        isHideTextUntilComplete(): boolean;
        hasAnyVisibleChildren(): boolean;
        setDefaultQuestShape(defaultQuestShape: string): void;
        getDefaultQuestShape(): string;
        addImage(image: $ChapterImage): void;
        hasGroup(): boolean;
        isAlwaysInvisible(): boolean;
        file: $BaseQuestFile;
        id: number;
        constructor(id: number, file: $BaseQuestFile, group: $ChapterGroup);
        constructor(id: number, file: $BaseQuestFile, group: $ChapterGroup, filename: string);
        get index(): number;
        get filename(): string;
        get group(): $ChapterGroup;
        get images(): $List<$ChapterImage>;
        get hideQuestUntilDepsVisible(): boolean;
        get defaultQuestSize(): number;
        get defaultRepeatable(): boolean;
        get requireSequentialTasks(): boolean;
        get altTitle(): $MutableComponent;
        get questLinks(): $List<$QuestLink>;
        get progressionMode(): $ProgressionMode;
        get quests(): $List<$Quest>;
        get defaultMinWidth(): number;
        get hideTextUntilComplete(): boolean;
        get alwaysInvisible(): boolean;
    }
    export class $QuestObjectBase implements $Comparable<$QuestObjectBase> {
        compareTo(other: $QuestObjectBase): number;
        getId(): number;
        static copy<T extends $QuestObjectBase>(orig: T, factory: $Supplier_<T>): T;
        static isNull(object: $QuestObjectBase): boolean;
        getPath(): (string) | undefined;
        static getID(object: $QuestObjectBase): number;
        getObjectType(): $QuestObjectType;
        getIcon(): $Icon;
        isValid(): boolean;
        getTitle(): $Component;
        hasTag(tag: string): boolean;
        getQuestFile(): $BaseQuestFile;
        writeData(nbt: $CompoundTag_, provider: $HolderLookup$Provider): void;
        holderLookup(): $HolderLookup$Provider;
        getTags(): $Set<string>;
        readData(nbt: $CompoundTag_, provider: $HolderLookup$Provider): void;
        onCreated(): void;
        static singleItemOrMissingFromNBT(tag: $Tag_, provider: $HolderLookup$Provider): $ItemStack;
        getProtoTranslation(key: $TranslationKey_): string;
        static shouldSendNotifications(): boolean;
        onEditButtonClicked(gui: $Runnable_): void;
        editedFromGUIOnServer(): void;
        fillConfigGroup(config: $ConfigGroup): void;
        readNetData(buffer: $RegistryFriendlyByteBuf): void;
        static parseCodeString(id: string): number;
        writeNetData(buffer: $RegistryFriendlyByteBuf): void;
        getAltTitle(): $Component;
        getParentID(): number;
        setRawTitle(rawTitle: string): void;
        clearCachedData(): void;
        deleteChildren(): void;
        deleteSelf(): void;
        getAltIcon(): $Icon;
        static itemOrMissingFromNBT(tag: $Tag_, provider: $HolderLookup$Provider): $ItemStack;
        componentsToRefresh(): $Set<$RecipeModHelper$Components>;
        static getCodeString(object: $QuestObjectBase): string;
        static getCodeString(id: number): string;
        getCodeString(): string;
        modifyTranslatableListValue(translationKey: $TranslationKey_, setter: $Consumer_<$List<string>>): void;
        setRawIcon(rawIcon: $ItemStack_): void;
        static titleToID(s: string): (string) | undefined;
        static parseHexId(id: string): (number) | undefined;
        forceProgressRaw(teamData: $TeamData, progressChange: $ProgressChange): void;
        getQuestChapter(): $Chapter;
        forceProgress(teamData: $TeamData, progressChange: $ProgressChange): void;
        getRawTitle(): string;
        createSubGroup(group: $ConfigGroup): $ConfigGroup;
        getMutableTitle(): $MutableComponent;
        editedFromGUI(): void;
        id: number;
        constructor(id: number);
        get path(): (string) | undefined;
        get objectType(): $QuestObjectType;
        get icon(): $Icon;
        get valid(): boolean;
        get title(): $Component;
        get questFile(): $BaseQuestFile;
        get tags(): $Set<string>;
        get altTitle(): $Component;
        get parentID(): number;
        get altIcon(): $Icon;
        set rawIcon(value: $ItemStack_);
        get questChapter(): $Chapter;
        get mutableTitle(): $MutableComponent;
    }
    export class $TeamData {
        isStarted(object: $QuestObject): boolean;
        getName(): string;
        static get(player: $Player): $TeamData;
        setName(name: string): void;
        getFile(): $BaseQuestFile;
        isLocked(): boolean;
        setCompleted(id: number, time: $Date): boolean;
        isCompleted(object: $QuestObject): boolean;
        copyData(from: $TeamData): void;
        setStarted(questId: number, time: $Date): boolean;
        getProgress(taskId: number): number;
        getProgress(task: $Task): number;
        saveIfChanged(): void;
        getTeamId(): $UUID;
        serializeNBT(): $SNBTCompoundTag;
        deserializeNBT(nbt: $SNBTCompoundTag): void;
        markDirty(): void;
        setProgress(task: $Task, progress: number): void;
        setLocked(newLocked: boolean): boolean;
        getOnlineMembers(): $Collection<$ServerPlayer>;
        isExcludedByOtherQuestline(qo: $QuestObject): boolean;
        areDependenciesVisible(quest: $Quest): boolean;
        getCanEdit(player: $Player): boolean;
        resetProgress(task: $Task): void;
        canStartTasks(quest: $Quest): boolean;
        markTaskCompleted(task: $Task): void;
        setCanEdit(player: $Player, newCanEdit: boolean): boolean;
        resetReward(player: $UUID_, reward: $Reward): boolean;
        claimReward(player: $ServerPlayer, reward: $Reward, notify: boolean, when: number): void;
        claimReward(player: $ServerPlayer, reward: $Reward, notify: boolean): void;
        deleteReward(reward: $Reward): void;
        isRewardClaimed(player: $UUID_, reward: $Reward): boolean;
        isRewardBlocked(reward: $Reward): boolean;
        getCompletionCount(quest: $Quest): number;
        getClaimType(player: $UUID_, reward: $Reward): $RewardClaimType;
        addProgress(task: $Task, progress: number): void;
        getRewardClaimTime(player: $UUID_, reward: $Reward): ($Date) | undefined;
        getCompletedTime(questId: number): ($Date) | undefined;
        setRewardsBlocked(rewardsBlocked: boolean): boolean;
        areRewardsBlocked(): boolean;
        getStartedTime(questId: number): ($Date) | undefined;
        getPinnedQuestIds(player: $Player): $LongSet;
        getCannotStartReason(quest: $Quest): $Component;
        markRewardAsClaimed(player: $UUID_, reward: $Reward, date: number): boolean;
        setQuestPinned(player: $Player, id: number, pinned: boolean): void;
        isQuestPinned(player: $Player, id: number): boolean;
        hasUnclaimedRewards(player: $UUID_, object: $QuestObject): boolean;
        clearCachedProgress(): void;
        getRelativeProgress(object: $QuestObject): number;
        clearRepeatCooldown(q: $Quest): void;
        areDependenciesComplete(quest: $Quest): boolean;
        mergeClaimedRewards(from: $TeamData): void;
        checkAutoCompletion(quest: $Quest): void;
        getMilliSecondsUntilRepeatable(quest: $Quest): number;
        mergeData(from: $TeamData): void;
        static AUTO_PIN_ID: number;
        static VERSION: number;
        static STREAM_CODEC: $StreamCodec<$FriendlyByteBuf, $TeamData>;
        constructor(teamId: $UUID_, file: $BaseQuestFile);
        constructor(teamId: $UUID_, file: $BaseQuestFile, name: string);
        get file(): $BaseQuestFile;
        get teamId(): $UUID;
        get onlineMembers(): $Collection<$ServerPlayer>;
        set rewardsBlocked(value: boolean);
    }
    export class $ChapterGroup extends $QuestObject {
        getFile(): $BaseQuestFile;
        getChapters(): $List<$Chapter>;
        sortChapters(c: $Comparator<$Chapter>): void;
        isDefaultGroup(): boolean;
        getVisibleChapters(data: $TeamData): $List<$Chapter>;
        clearChapters(): void;
        addChapter(chapter: $Chapter): void;
        moveChapterWithinGroup(chapter: $Chapter, movingUp: boolean): boolean;
        toggleCollapsed(): void;
        isFirstGroup(): boolean;
        isGuiCollapsed(): boolean;
        isLastGroup(): boolean;
        removeChapter(chapter: $Chapter): void;
        getFirstVisibleChapter(data: $TeamData): $Chapter;
        id: number;
        constructor(id: number, file: $BaseQuestFile);
        get file(): $BaseQuestFile;
        get chapters(): $List<$Chapter>;
        get defaultGroup(): boolean;
        get firstGroup(): boolean;
        get guiCollapsed(): boolean;
        get lastGroup(): boolean;
    }
    export class $ProgressionMode extends $Enum<$ProgressionMode> {
        static values(): $ProgressionMode[];
        static valueOf(name: string): $ProgressionMode;
        getId(): string;
        static NAME_MAP: $NameMap<$ProgressionMode>;
        static NAME_MAP_NO_DEFAULT: $NameMap<$ProgressionMode>;
        static LINEAR: $ProgressionMode;
        static DEFAULT: $ProgressionMode;
        static FLEXIBLE: $ProgressionMode;
        get id(): string;
    }
    /**
     * Values that may be interpreted as {@link $ProgressionMode}.
     */
    export type $ProgressionMode_ = "default" | "linear" | "flexible";
}
