import { $AbstractTackleSkin } from "@package/com/wdiscute/starcatcher/registry/tackleskin";
import { $PanoramaRenderer } from "@package/net/minecraft/client/renderer";
import { $ItemStack_, $ItemStack } from "@package/net/minecraft/world/item";
import { $NarratableEntry } from "@package/net/minecraft/client/gui/narration";
import { $Component } from "@package/net/minecraft/network/chat";
import { $Renderable } from "@package/net/minecraft/client/gui/components";
import { $AbstractMinigameModifier } from "@package/com/wdiscute/starcatcher/registry/minigamemodifiers";
import { $List, $Map } from "@package/java/util";
import { $Supplier } from "@package/java/util/function";
import { $InteractionHand } from "@package/net/minecraft/world";
import { $Screen, $Screen$DeferredTooltipRendering } from "@package/net/minecraft/client/gui/screens";
import { $ResourceLocation_, $ResourceLocation } from "@package/net/minecraft/resources";
import { $PoseStack } from "@package/com/mojang/blaze3d/vertex";
import { $FishProperties$SweetSpot_, $FishProperties$SweetSpot, $FishProperties$Difficulty, $FishProperties_, $FishProperties$Rarity } from "@package/com/wdiscute/starcatcher/registry";
import { $Object } from "@package/java/lang";
import { $Font, $GuiGraphics } from "@package/net/minecraft/client/gui";
import { $GuiEventListener } from "@package/net/minecraft/client/gui/components/events";
import { $AbstractSweetSpotBehaviour } from "@package/com/wdiscute/starcatcher/registry/sweetspotbehaviour";

declare module "@package/com/wdiscute/starcatcher/minigame" {
    export class $ActiveSweetSpot {
        isHoveredOver(): boolean;
        reward: number;
        vanishingRate: number;
        instance: $FishingMinigameScreen;
        bait: $ItemStack;
        thickness: number;
        extraData: $Map<number, $Object>;
        texture: $ResourceLocation;
        onHitModifiers: $List<$Supplier<$AbstractMinigameModifier>>;
        shouldSudokuOnVanish: boolean;
        hook: $ItemStack;
        removed: boolean;
        isFlip: boolean;
        pos: number;
        baseSS: $FishProperties$SweetSpot;
        alpha: number;
        particleColor: number;
        behaviour: $AbstractSweetSpotBehaviour;
        currentRotation: number;
        bobber: $ItemStack;
        movingRate: number;
        constructor(arg0: $FishingMinigameScreen, arg1: $FishProperties$SweetSpot_, arg2: $ItemStack_, arg3: $ItemStack_, arg4: $ItemStack_);
        constructor(arg0: $FishingMinigameScreen, arg1: $FishProperties$SweetSpot_);
        get hoveredOver(): boolean;
    }
    export class $FishingMinigameScreen extends $Screen implements $GuiEventListener {
        getModifiers(): $List<$AbstractMinigameModifier>;
        renderKimbeMarker(arg0: $GuiGraphics): void;
        removeAllSweetSpots(): void;
        addModifier(arg0: $AbstractMinigameModifier): void;
        addParticles(arg0: number, arg1: number, arg2: number): void;
        getActiveSweetSpots(): $List<$ActiveSweetSpot>;
        static renderPoseCentered(arg0: $GuiGraphics, arg1: $ResourceLocation_, arg2: number, arg3: number, arg4: number, arg5: number, arg6: number): void;
        static renderPoseCentered(arg0: $GuiGraphics, arg1: $ResourceLocation_, arg2: number): void;
        addUniqueModifier(arg0: $AbstractMinigameModifier): void;
        getPointerPosPrecise(): number;
        refreshSweetSpotsAlphas(): void;
        addSweetSpot(arg0: $ActiveSweetSpot): void;
        getRandomFreePosition(arg0: number): number;
        renderTreasure(arg0: $GuiGraphics): void;
        renderPointer(arg0: $GuiGraphics, arg1: $PoseStack, arg2: number): void;
        isHoldingInput(): boolean;
        isSettingsScreen(): boolean;
        renderSweetSpot(arg0: $ActiveSweetSpot, arg1: $GuiGraphics, arg2: number, arg3: $PoseStack): void;
        static hasDistantHorizons(): boolean;
        inputPressed(): void;
        static clampPos(arg0: number): number;
        static doDegreesOverlapWithLeeway(arg0: number, arg1: number, arg2: number): boolean;
        consecutiveHits: number;
        static MENU_BACKGROUND: $ResourceLocation;
        yOffset: number;
        bait: $ItemStack;
        holdingDelay: number;
        static INWORLD_FOOTER_SEPARATOR: $ResourceLocation;
        hp: number;
        decay: number;
        handToSwing: $InteractionHand;
        kimbeMarkerColor: number;
        pointerBaseSpeed: number;
        renderables: $List<$Renderable>;
        hook: $ItemStack;
        tickCount: number;
        renderScale: number;
        static PANORAMA: $PanoramaRenderer;
        pointerPos: number;
        holdingTicks: number;
        pointerSpeed: number;
        treasureActive: boolean;
        static HEADER_SEPARATOR: $ResourceLocation;
        height: number;
        xOffset: number;
        itemBeingFished: $ItemStack;
        treasureIS: $ItemStack;
        difficulty: $FishProperties$Difficulty;
        progressSmooth: number;
        static TEXTURE: $ResourceLocation;
        perfectCatch: boolean;
        partial: number;
        rarity: $FishProperties$Rarity;
        bobber: $ItemStack;
        gracePeriod: number;
        penalty: number;
        title: $Component;
        static INWORLD_HEADER_SEPARATOR: $ResourceLocation;
        treasureProgress: number;
        tankTexture: $ResourceLocation;
        deferredTooltipRendering: $Screen$DeferredTooltipRendering;
        treasureProgressSmooth: number;
        kimbeMarkerPos: number;
        tackleSkin: $AbstractTackleSkin;
        static FOOTER_SEPARATOR: $ResourceLocation;
        kimbeMarkerAlpha: number;
        hitDelay: number;
        narratables: $List<$NarratableEntry>;
        width: number;
        progress: number;
        minigameStarted: boolean;
        currentRotation: number;
        font: $Font;
        constructor(arg0: $FishProperties_, arg1: $ItemStack_);
        get modifiers(): $List<$AbstractMinigameModifier>;
        get activeSweetSpots(): $List<$ActiveSweetSpot>;
        get pointerPosPrecise(): number;
        get holdingInput(): boolean;
        get settingsScreen(): boolean;
    }
}
