import { $IFilterConfigurable } from "@package/com/klikli_dev/occultism/common/entity";
import { $ExtendedSensor } from "@package/net/tslat/smartbrainlib/api/core/sensor";
import { $GoalSelector } from "@package/net/minecraft/world/entity/ai/goal";
import { $MoveControl, $LookControl } from "@package/net/minecraft/world/entity/ai/control";
import { $MinecraftServer } from "@package/net/minecraft/server";
import { $CompoundTag_ } from "@package/net/minecraft/nbt";
import { $SpellData } from "@package/io/redspace/ironsspellbooks/api/spells";
import { $EntityType_, $PortalProcessor, $Pose_, $EntityType, $EntityDimensions, $Entity$RemovalReason, $TamableAnimal, $LivingEntity, $WalkAnimationState } from "@package/net/minecraft/world/entity";
import { $AttributeSupplier$Builder } from "@package/net/minecraft/world/entity/ai/attributes";
import { $Activity } from "@package/net/minecraft/world/entity/schedule";
import { $UUID, $HashMap, $List, $UUID_, $Stack, $Map, $Set } from "@package/java/util";
import { $MenuProvider, $InteractionHand } from "@package/net/minecraft/world";
import { $WorkAreaSize, $WorkAreaSize_ } from "@package/com/klikli_dev/occultism/api/common/data";
import { $HolderLookup$Provider, $BlockPos, $Holder, $BlockPos_, $Direction_, $NonNullList, $Direction } from "@package/net/minecraft/core";
import { $SmartBrainOwner } from "@package/net/tslat/smartbrainlib/api";
import { $RegistryFriendlyByteBuf } from "@package/net/minecraft/network";
import { $SoundInstance } from "@package/net/minecraft/client/resources/sounds";
import { $AbstractContainerMenu } from "@package/net/minecraft/world/inventory";
import { $LootTable } from "@package/net/minecraft/world/level/storage/loot";
import { $Level, $Level_ } from "@package/net/minecraft/world/level";
import { $SmartBrain, $BrainActivityGroup } from "@package/net/tslat/smartbrainlib/api/core";
import { $ItemStack } from "@package/net/minecraft/world/item";
import { $SpiritJob } from "@package/com/klikli_dev/occultism/common/entity/job";
import { $ItemStackHandler } from "@package/net/neoforged/neoforge/items";
import { $MobEffectInstance, $MobEffect } from "@package/net/minecraft/world/effect";
import { $Player, $Inventory } from "@package/net/minecraft/world/entity/player";
import { $ItemEntity } from "@package/net/minecraft/world/entity/item";
import { $EntityDataAccessor_, $EntityDataAccessor, $SynchedEntityData$Builder } from "@package/net/minecraft/network/syncher";
import { $ResourceKey } from "@package/net/minecraft/resources";
import { $SmartBrainSchedule } from "@package/net/tslat/smartbrainlib/api/core/schedule";
import { $Vec3 } from "@package/net/minecraft/world/phys";

declare module "@package/com/klikli_dev/occultism/common/entity/spirit" {
    export class $SpiritEntity extends $TamableAnimal implements $ISkinnedCreatureMixin, $MenuProvider, $SmartBrainOwner<$SpiritEntity>, $IFilterConfigurable {
        init(): void;
        setSpiritMaxAge(arg0: number): void;
        getSensors(): $List<$ExtendedSensor<$SpiritEntity>>;
        isInitialized(): boolean;
        getEntity(): $LivingEntity;
        getInventory(): $ItemStackHandler;
        getJob(): ($SpiritJob) | undefined;
        getWorkAreaSize(): $WorkAreaSize;
        openScreen(arg0: $Player): void;
        getSpiritMaxAge(): number;
        createMenu(arg0: number, arg1: $Inventory, arg2: $Player): $AbstractContainerMenu;
        handleAdditionalBrainSetup(arg0: $SmartBrain<$SpiritEntity>): void;
        getDefaultDimensions(arg0: $Pose_): $EntityDimensions;
        static createAttributes(): $AttributeSupplier$Builder;
        getExtractPosition(): ($BlockPos) | undefined;
        getDepositPosition(): ($BlockPos) | undefined;
        getJobID(): string;
        setJob(arg0: $SpiritJob, arg1: boolean): void;
        setJob(arg0: $SpiritJob): void;
        setDepositEntityUUID(arg0: $UUID_): void;
        canPickupItem(arg0: $ItemEntity): boolean;
        getFilterItems(): $ItemStackHandler;
        getDepositFacing(): $Direction;
        remakeBrain(): void;
        getCoreTasks(): $BrainActivityGroup<$SpiritEntity>;
        getIdleTasks(): $BrainActivityGroup<$SpiritEntity>;
        getWorkAreaCenter(): $BlockPos;
        setJobID(arg0: string): void;
        removeJob(): void;
        getWorkAreaPosition(): ($BlockPos) | undefined;
        getDepositEntityUUID(): ($UUID) | undefined;
        setWorkAreaPosition(arg0: $BlockPos_): void;
        getDataParameterSkin(): $EntityDataAccessor<number>;
        setTagFilter(arg0: string): void;
        getTagFilter(): string;
        setSpiritAge(arg0: number): void;
        setExtractPosition(arg0: $BlockPos_): void;
        getExtractFacing(): $Direction;
        setFilterBlacklist(arg0: boolean): void;
        isFilterBlacklist(): boolean;
        getSpiritAge(): number;
        setExtractFacing(arg0: $Direction_): void;
        setWorkAreaSize(arg0: $WorkAreaSize_): void;
        canDieFromAge(): boolean;
        setDepositPosition(arg0: $BlockPos_): void;
        setDepositFacing(arg0: $Direction_): void;
        registerSkinDataParameter(arg0: $SynchedEntityData$Builder): void;
        getSkinTypes(): number;
        writeSkinToNBT(arg0: $CompoundTag_): void;
        readSkinFromNBT(arg0: $CompoundTag_): void;
        selectRandomSkin(): void;
        getSchedule(): $SmartBrainSchedule;
        getScheduleIgnoringActivities(): $Set<$Activity>;
        tickBrain(arg0: $SpiritEntity): void;
        getActivityPriorities(): $List<$Activity>;
        getAlwaysRunningActivities(): $Set<$Activity>;
        getFightTasks(): $BrainActivityGroup<$SpiritEntity>;
        getDefaultActivity(): $Activity;
        getAdditionalTasks(): $Map<$Activity, $BrainActivityGroup<$SpiritEntity>>;
        writeClientSideData(arg0: $AbstractContainerMenu, arg1: $RegistryFriendlyByteBuf): void;
        shouldTriggerClientSideContainerClosingOnOpen(): boolean;
        serializeNBT(arg0: $HolderLookup$Provider): $SpiritEntity;
        static MAX_WEARING_ARMOR_CHANCE: number;
        lastHurtByPlayerTime: number;
        static PRESERVE_ITEM_DROP_CHANCE_THRESHOLD: number;
        armorItems: $NonNullList<$ItemStack>;
        static DEFAULT_BASE_GRAVITY: number;
        xRot: number;
        hasImpulse: boolean;
        static USE_ITEM_INTERVAL: number;
        static MAX_PICKUP_LOOT_CHANCE: number;
        ars_Nouveau$motions: $Stack<any>;
        lootTable: $ResourceKey<$LootTable>;
        yHeadRot: number;
        an_isRewinding: boolean;
        noPhysics: boolean;
        fallFlyTicks: number;
        yo: number;
        yBodyRotO: number;
        removalReason: $Entity$RemovalReason;
        zza: number;
        goalSelector: $GoalSelector;
        handDropChances: number[];
        swingingArm: $InteractionHand;
        static ID_TAG: string;
        armorDropChances: number[];
        persistenceRequired: boolean;
        static DELTA_AFFECTED_BY_BLOCKS_BELOW_1_0: number;
        xRotO: number;
        zo: number;
        s_bee: $EntityType<any>;
        walkDist: number;
        lastHurt: number;
        noCulling: boolean;
        walkAnimation: $WalkAnimationState;
        yya: number;
        oAttackAnim: number;
        yHeadRotO: number;
        static UUID_TAG: string;
        hurtDuration: number;
        static TELEPORT_WHEN_DISTANCE_IS_SQ: number;
        static DEATH_DURATION: number;
        portalProcess: $PortalProcessor;
        dead: boolean;
        verticalCollision: boolean;
        verticalCollisionBelow: boolean;
        static DEFAULT_BABY_SCALE: number;
        eyeHeight: number;
        static ATTRIBUTES_FIELD: string;
        static SKIN: $EntityDataAccessor<number>;
        static UPDATE_GOAL_SELECTOR_EVERY_N_TICKS: number;
        static DEFAULT_BB_HEIGHT: number;
        xxa: number;
        static MAX_FILTER_SLOTS: number;
        flyDist: number;
        static PASSENGERS_TAG: string;
        wasOnFire: boolean;
        attackAnim: number;
        zOld: number;
        static BABY_START_AGE: number;
        timeOffs: number;
        handItems: $NonNullList<$ItemStack>;
        wasTouchingWater: boolean;
        activeEffects: $Map<$Holder<$MobEffect>, $MobEffectInstance>;
        rotA: number;
        horizontalCollision: boolean;
        dimensions: $EntityDimensions;
        castingSpell: $SpellData;
        static DEFAULT_EQUIPMENT_DROP_CHANCE: number;
        static ARMOR_SLOT_OFFSET: number;
        swingTime: number;
        the_server: $MinecraftServer;
        static BODY_ARMOR_OFFSET: number;
        stuckSpeedMultiplier: $Vec3;
        tickCount: number;
        static MAX_ENCHANTED_ARMOR_CHANCE: number;
        static MAX_ENCHANTED_WEAPON_CHANCE: number;
        hasUsedSingleAttack: boolean;
        lastHurtByPlayer: $Player;
        static BOARDING_COOLDOWN: number;
        static PRESERVE_ITEM_DROP_CHANCE: number;
        static SWING_DURATION: number;
        yRotO: number;
        static MIN_MOVEMENT_DISTANCE: number;
        static CONTENTS_SLOT_INDEX: number;
        static BASE_JUMP_POWER: number;
        level: $Level;
        ambientSoundTime: number;
        yRot: number;
        static DEFAULT_MAX_AGE: number;
        moveDist: number;
        mainSupportingBlockPos: ($BlockPos) | undefined;
        targetSelector: $GoalSelector;
        lookControl: $LookControl;
        drinkTime: number;
        create_diesel_generators$turretPos: $BlockPos;
        xOld: number;
        wasInPowderSnow: boolean;
        hurtTime: number;
        xpReward: number;
        swinging: boolean;
        hurtMarked: boolean;
        attackStrengthTicker: number;
        deathTime: number;
        static EQUIPMENT_SLOT_OFFSET: number;
        sounds$currentSwordSwooshSound: $SoundInstance;
        invulnerableTime: number;
        jumping: boolean;
        moveControl: $MoveControl;
        static BASE_TICKS_REQUIRED_TO_FREEZE: number;
        fallDistance: number;
        filterItemStackHandler: $ItemStackHandler;
        inventory: $ItemStackHandler;
        static DELTA_AFFECTED_BY_BLOCKS_BELOW_0_5: number;
        static MAX_ENTITY_TAG_COUNT: number;
        static ARMOR_SLOTS: number;
        static DELTA_AFFECTED_BY_BLOCKS_BELOW_0_2: number;
        static PLAYER_HURT_EXPERIENCE_TIME: number;
        yOld: number;
        static HAND_SLOTS: number;
        static DEFAULT_BB_WIDTH: number;
        minorHorizontalCollision: boolean;
        spells: $HashMap<any, any>;
        static EXTRA_RENDER_CULLING_SIZE_WITH_BIG_HAT: number;
        removeArrowTime: number;
        walkDistO: number;
        static FREEZE_HURT_FREQUENCY: number;
        isInPowderSnow: boolean;
        static ATTACHMENTS_NBT_KEY: string;
        yBodyRot: number;
        blocksBuilding: boolean;
        static TOTAL_AIR_SUPPLY: number;
        xo: number;
        invulnerableDuration: number;
        removeStingerTime: number;
        static BASE_SAFE_FALL_DISTANCE: number;
        effectsDirty: boolean;
        constructor(arg0: $EntityType_<$SpiritEntity>, arg1: $Level_);
        constructor(arg0: $EntityType_<$SpiritEntity>, arg1: $Level_, arg2: $ItemStackHandler);
        get sensors(): $List<$ExtendedSensor<$SpiritEntity>>;
        get initialized(): boolean;
        get entity(): $LivingEntity;
        get filterItems(): $ItemStackHandler;
        get coreTasks(): $BrainActivityGroup<$SpiritEntity>;
        get idleTasks(): $BrainActivityGroup<$SpiritEntity>;
        get workAreaCenter(): $BlockPos;
        get dataParameterSkin(): $EntityDataAccessor<number>;
        get skinTypes(): number;
        get schedule(): $SmartBrainSchedule;
        get scheduleIgnoringActivities(): $Set<$Activity>;
        get activityPriorities(): $List<$Activity>;
        get alwaysRunningActivities(): $Set<$Activity>;
        get fightTasks(): $BrainActivityGroup<$SpiritEntity>;
        get defaultActivity(): $Activity;
        get additionalTasks(): $Map<$Activity, $BrainActivityGroup<$SpiritEntity>>;
    }
    export class $ISkinnedCreatureMixin {
    }
    export interface $ISkinnedCreatureMixin {
        getEntity(): $LivingEntity;
        registerSkinDataParameter(arg0: $SynchedEntityData$Builder): void;
        getDataParameterSkin(): $EntityDataAccessor<number>;
        getSkinTypes(): number;
        writeSkinToNBT(arg0: $CompoundTag_): void;
        readSkinFromNBT(arg0: $CompoundTag_): void;
        selectRandomSkin(): void;
        get entity(): $LivingEntity;
        get dataParameterSkin(): $EntityDataAccessor<number>;
        get skinTypes(): number;
    }
    /**
     * Values that may be interpreted as {@link $ISkinnedCreatureMixin}.
     */
    export type $ISkinnedCreatureMixin_ = (() => $EntityDataAccessor_<number>);
}
