import { $KeyModifier } from "@package/net/neoforged/neoforge/client/settings";
import { $KJSCTTypeWrapper, $KJSSpriteShiftWrapper } from "@package/fr/iglee42/createcasing/kubejs/wrappers";
import { $NumberProviderWrapper } from "@package/com/almostreliable/lootjs/kube/wrappers";
import { $EffectInstanceBinding, $CrushingResultBinding } from "@package/com/almostreliable/kubeaa/binding";
import { $SpellData, $SpellRarity, $CastType } from "@package/io/redspace/ironsspellbooks/api/spells";
import { $IsInBiomeWithTagConditionWrapper, $IsInDimensionTypeConditionWrapper, $IsInDimensionConditionWrapper, $IsInBiomeConditionWrapper, $EntityToSacrificeWrapper, $WeightedRecipeResultWrapper, $RecipeResultWrapper } from "@package/com/klikli_dev/occultism_kubejs/component";
import { $Minecraft } from "@package/net/minecraft/client";
import { $TargetEntityCastData } from "@package/io/redspace/ironsspellbooks/capabilities/magic";
import { $AbstractMap } from "@package/java/util";
import { $ParticleHelper } from "@package/io/redspace/ironsspellbooks/util";
import { $KeyBindUtil } from "@package/com/common/keybindjs/kubejs";
import { $LootCondition, $Predicates, $LootFunction } from "@package/com/almostreliable/lootjs/loot";
import { $BlockPos, $Vec3i } from "@package/net/minecraft/core";
import { $RotationAxis, $NBTIOWrapper, $MobEffectUtil, $JsonUtils, $NotificationToastData, $JsonIO, $ID, $FluidAmounts } from "@package/dev/latvian/mods/kubejs/util";
import { $GustDefenseGoal, $SpellBarrageGoal, $WizardRecoverGoal, $WarlockAttackGoal, $WizardSupportGoal, $WizardAttackGoal, $WispAttackGoal } from "@package/io/redspace/ironsspellbooks/entity/mobs/goals";
import { $LootType } from "@package/com/almostreliable/lootjs/core";
import { $ItemFilter } from "@package/com/almostreliable/lootjs/core/filters";
import { $GeneratorsCreateOutput } from "@package/dev/bluephs/createvintageneoforged/compat/kubejs/wrapper";
import { $Math } from "@package/java/lang";
import { $ConsoleJS, $PlatformWrapper } from "@package/dev/latvian/mods/kubejs/script";
import { $ReplicationKubeJSGateway } from "@package/com/buuz135/replication/integration/kubejs";
import { $ItemTags } from "@package/net/minecraft/tags";
import { $FTBQuestsKubeJSWrapper } from "@package/dev/ftb/mods/ftbxmodcompat/neoforge/ftbquests/kubejs";
import { $BlockStatePredicate } from "@package/dev/latvian/mods/kubejs/block/state";
import { $Items } from "@package/net/minecraft/world/item";
import { $FluidWrapper } from "@package/dev/latvian/mods/kubejs/fluid";
import { $MobEffects } from "@package/net/minecraft/world/effect";
import { $KubeCreateOutput } from "@package/dev/latvian/mods/kubejs/create/wrapper";
import { $Player } from "@package/net/minecraft/world/entity/player";
import { $KMath, $TextWrapper, $IngredientWrapper, $SizedIngredientWrapper, $UUIDWrapper, $ParticleOptionsWrapper, $RegistryWrapper, $EntitySelectorWrapper, $NBTWrapper, $BlockWrapper, $DirectionWrapper, $NativeEventWrapper, $JavaWrapper, $UtilsWrapper, $TextIcons, $ColorWrapper, $AABBWrapper, $StringUtilsWrapper, $ItemWrapper, $DataMapWrapper } from "@package/dev/latvian/mods/kubejs/plugin/builtin/wrapper";
import { $AbstractSpellWrapper } from "@package/com/squoshi/irons_spells_js/spell";
import { $ProcessingOutput } from "@package/com/simibubi/create/content/processing/recipe";
import { $AnimationHolder, $Utils } from "@package/io/redspace/ironsspellbooks/api/util";
import { $SchoolRegistry, $SpellRegistry } from "@package/io/redspace/ironsspellbooks/api/registry";
import { $MinMaxBounds$Doubles, $LocationPredicate, $ItemPredicate, $MobEffectsPredicate, $DistancePredicate, $EntityEquipmentPredicate, $EnchantmentPredicate, $BlockPredicate, $NbtPredicate, $LightPredicate, $FluidPredicate, $EntityPredicate } from "@package/net/minecraft/advancements/critereon";
import { $Duration } from "@package/java/time";
import { $BlockStateProperties } from "@package/net/minecraft/world/level/block/state/properties";
import { $AlmostKube } from "@package/com/almostreliable/unified/compat/kube";
import { $Potions } from "@package/net/minecraft/world/item/alchemy";
import { $MekanismChemicalWrapper } from "@package/dev/latvian/mods/kubejs/mekanism";
import { $GLFW } from "@package/org/lwjgl/glfw";
import { $SDRPKubeJSWrapper } from "@package/com/sunekaer/sdrp/neoforge/kubejs";
import { $SoundType, $Blocks } from "@package/net/minecraft/world/level/block";
import { $LootEntry } from "@package/com/almostreliable/lootjs/core/entry";
import { $Vec3 } from "@package/net/minecraft/world/phys";
import { $Stats } from "@package/net/minecraft/stats";
import { $PotionRegistry } from "@package/io/redspace/ironsspellbooks/registries";
import { $DamageSource } from "@package/net/minecraft/world/damagesource";
import { $Matrix4f, $Vector4f, $Vector3f, $Quaternionf, $Matrix3f } from "@package/org/joml";

declare module "@side-only/server/bindings" {
}

export {};

declare global {
    let global: {};
    let Platform: typeof $PlatformWrapper;
    let console: $ConsoleJS;
    let JavaMath: typeof $Math;
    let ID: typeof $ID;
    let Duration: typeof $Duration;
    let KMath: typeof $KMath;
    let Utils: typeof $UtilsWrapper;
    let StringUtils: typeof $StringUtilsWrapper;
    let Java: typeof $JavaWrapper;
    let Text: typeof $TextWrapper;
    let Component: typeof $TextWrapper;
    let TextIcons: typeof $TextIcons;
    let UUID: typeof $UUIDWrapper;
    let JsonUtils: typeof $JsonUtils;
    let JsonIO: typeof $JsonIO;
    let Block: typeof $BlockWrapper;
    let Blocks: typeof $Blocks;
    let Item: typeof $ItemWrapper;
    let Items: typeof $Items;
    let Ingredient: typeof $IngredientWrapper;
    let NBT: typeof $NBTWrapper;
    let NBTIO: typeof $NBTIOWrapper;
    let Direction: typeof $DirectionWrapper;
    let Facing: typeof $DirectionWrapper;
    let AABB: typeof $AABBWrapper;
    let Stats: typeof $Stats;
    let FluidAmounts: typeof $FluidAmounts;
    let Notification: typeof $NotificationToastData;
    let SizedIngredient: typeof $SizedIngredientWrapper;
    let ParticleOptions: typeof $ParticleOptionsWrapper;
    let Registry: typeof $RegistryWrapper<any>;
    let DataMap: typeof $DataMapWrapper<any, any>;
    let EntitySelector: typeof $EntitySelectorWrapper;
    let Fluid: typeof $FluidWrapper;
    let SECOND: number;
    let MINUTE: number;
    let HOUR: number;
    let Color: typeof $ColorWrapper;
    let BlockStatePredicate: typeof $BlockStatePredicate;
    let Vec3d: typeof $Vec3;
    let Vec3i: typeof $Vec3i;
    let Vec3f: typeof $Vector3f;
    let Vec4f: typeof $Vector4f;
    let Matrix3f: typeof $Matrix3f;
    let Matrix4f: typeof $Matrix4f;
    let Quaternionf: typeof $Quaternionf;
    let RotationAxis: typeof $RotationAxis;
    let BlockPos: typeof $BlockPos;
    let DamageSource: typeof $DamageSource;
    let SoundType: typeof $SoundType;
    let BlockProperties: typeof $BlockStateProperties;
    let NativeEvents: typeof $NativeEventWrapper;
    let MobEffectUtil: typeof $MobEffectUtil;
    let Client: $Minecraft;
    let GLFWInput: $AbstractMap<any, any>;
    let SpellRarity: typeof $SpellRarity;
    let SchoolRegistry: typeof $SchoolRegistry;
    let CastType: typeof $CastType;
    let IronsSpellsParticleHelper: typeof $ParticleHelper;
    let SpellRegistry: typeof $SpellRegistry;
    let ItemTags: typeof $ItemTags;
    let Player: typeof $Player;
    let SpellData: typeof $SpellData;
    let Spell: typeof $AbstractSpellWrapper;
    let ISSAnimationHolder: typeof $AnimationHolder;
    let ISSUtils: typeof $Utils;
    let TargetEntityCastData: typeof $TargetEntityCastData;
    let Potions: typeof $Potions;
    let ISSPotionRegistry: typeof $PotionRegistry;
    let WizardAttackGoal: typeof $WizardAttackGoal;
    let WarlockAttackGoal: typeof $WarlockAttackGoal;
    let WizardRecoverGoal: typeof $WizardRecoverGoal;
    let WizardSupportGoal: typeof $WizardSupportGoal<any>;
    let SpellBarrageGoal: typeof $SpellBarrageGoal;
    let GustDefenseGoal: typeof $GustDefenseGoal;
    let WispAttackGoal: typeof $WispAttackGoal;
    let KeyBindUtil: $KeyBindUtil;
    let GLFW: typeof $GLFW;
    let KeyModifier: typeof $KeyModifier;
    let Replication: $ReplicationKubeJSGateway;
    let LootType: typeof $LootType;
    let ItemFilter: typeof $ItemFilter;
    let LootEntry: typeof $LootEntry;
    let LootCondition: $LootCondition;
    let LootFunction: $LootFunction;
    let Range: typeof $MinMaxBounds$Doubles;
    let NumberProvider: typeof $NumberProviderWrapper;
    let Predicates: typeof $Predicates;
    let ItemPredicate: typeof $ItemPredicate;
    let EntityPredicate: typeof $EntityPredicate;
    let EntityEquipmentPredicate: typeof $EntityEquipmentPredicate;
    let LocationPredicate: typeof $LocationPredicate;
    let DistancePredicate: typeof $DistancePredicate;
    let BlockPredicate: typeof $BlockPredicate;
    let FluidPredicate: typeof $FluidPredicate;
    let LightPredicate: typeof $LightPredicate;
    let EnchantmentPredicate: typeof $EnchantmentPredicate;
    let MobEffectsPredicate: typeof $MobEffectsPredicate;
    let NbtPredicate: typeof $NbtPredicate;
    let SDRP: typeof $SDRPKubeJSWrapper;
    let FTBQuests: $FTBQuestsKubeJSWrapper;
    let CrushingResult: typeof $CrushingResultBinding;
    let EffectInstance: typeof $EffectInstanceBinding;
    let MobEffect: typeof $MobEffects;
    let RecipeResult: typeof $RecipeResultWrapper;
    let WeightedRecipeResult: typeof $WeightedRecipeResultWrapper;
    let EntityToSacrifice: typeof $EntityToSacrificeWrapper;
    let IsInBiomeCondition: typeof $IsInBiomeConditionWrapper;
    let IsInBiomeWithTagCondition: typeof $IsInBiomeWithTagConditionWrapper;
    let IsInDimensionCondition: typeof $IsInDimensionConditionWrapper;
    let IsInDimensionTypeCondition: typeof $IsInDimensionTypeConditionWrapper;
    let MekanismChemical: typeof $MekanismChemicalWrapper;
    let Output: typeof $GeneratorsCreateOutput;
    let DgjsProcessingOutput: typeof $ProcessingOutput;
    let CreateProcessingOutput: typeof $ProcessingOutput;
    let CreateItem: typeof $KubeCreateOutput;
    let SpriteShifts: typeof $KJSSpriteShiftWrapper;
    let CTType: typeof $KJSCTTypeWrapper;
    let AlmostUnified: typeof $AlmostKube;
}
