export * as spells from "@package/io/redspace/ironsspellbooks/api/spells";
export * as config from "@package/io/redspace/ironsspellbooks/api/config";
export * as events from "@package/io/redspace/ironsspellbooks/api/events";
export * as network from "@package/io/redspace/ironsspellbooks/api/network";
export * as magic from "@package/io/redspace/ironsspellbooks/api/magic";
export * as entity from "@package/io/redspace/ironsspellbooks/api/entity";
export * as util from "@package/io/redspace/ironsspellbooks/api/util";
export * as registry from "@package/io/redspace/ironsspellbooks/api/registry";
export * as item from "@package/io/redspace/ironsspellbooks/api/item";
