import { $Serializable } from "@package/java/io";
import { $Shape, $Rectangle } from "@package/java/awt";
import { $Object, $Cloneable } from "@package/java/lang";

declare module "@package/java/awt/geom" {
    export class $Line2D implements $Shape, $Cloneable {
        clone(): $Object;
        contains(arg0: $Rectangle2D): boolean;
        contains(arg0: number, arg1: number): boolean;
        contains(arg0: $Point2D): boolean;
        contains(arg0: number, arg1: number, arg2: number, arg3: number): boolean;
        getBounds(): $Rectangle;
        intersects(arg0: $Rectangle2D): boolean;
        intersects(arg0: number, arg1: number, arg2: number, arg3: number): boolean;
        getPathIterator(arg0: $AffineTransform, arg1: number): $PathIterator;
        getPathIterator(arg0: $AffineTransform): $PathIterator;
        relativeCCW(arg0: $Point2D): number;
        static relativeCCW(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number): number;
        relativeCCW(arg0: number, arg1: number): number;
        ptSegDistSq(arg0: number, arg1: number): number;
        static ptSegDistSq(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number): number;
        ptSegDistSq(arg0: $Point2D): number;
        ptSegDist(arg0: number, arg1: number): number;
        ptSegDist(arg0: $Point2D): number;
        static ptSegDist(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number): number;
        ptLineDistSq(arg0: $Point2D): number;
        static ptLineDistSq(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number): number;
        ptLineDistSq(arg0: number, arg1: number): number;
        ptLineDist(arg0: number, arg1: number): number;
        ptLineDist(arg0: $Point2D): number;
        static ptLineDist(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number): number;
        setLine(arg0: $Point2D, arg1: $Point2D): void;
        setLine(arg0: $Line2D): void;
        setLine(arg0: number, arg1: number, arg2: number, arg3: number): void;
        getX1(): number;
        getY1(): number;
        getX2(): number;
        getY2(): number;
        intersectsLine(arg0: number, arg1: number, arg2: number, arg3: number): boolean;
        intersectsLine(arg0: $Line2D): boolean;
        getP1(): $Point2D;
        getP2(): $Point2D;
        static linesIntersect(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: number, arg7: number): boolean;
        get bounds(): $Rectangle;
        get x1(): number;
        get y1(): number;
        get x2(): number;
        get y2(): number;
        get p1(): $Point2D;
        get p2(): $Point2D;
    }
    export class $AffineTransform implements $Cloneable, $Serializable {
        clone(): $Object;
        scale(arg0: number, arg1: number): void;
        transform(arg0: number[], arg1: number, arg2: number[], arg3: number, arg4: number): void;
        transform(arg0: $Point2D, arg1: $Point2D): $Point2D;
        transform(arg0: number[], arg1: number, arg2: number[], arg3: number, arg4: number): void;
        transform(arg0: number[], arg1: number, arg2: number[], arg3: number, arg4: number): void;
        transform(arg0: $Point2D[], arg1: number, arg2: $Point2D[], arg3: number, arg4: number): void;
        transform(arg0: number[], arg1: number, arg2: number[], arg3: number, arg4: number): void;
        getType(): number;
        isIdentity(): boolean;
        rotate(arg0: number, arg1: number, arg2: number): void;
        rotate(arg0: number, arg1: number, arg2: number, arg3: number): void;
        rotate(arg0: number): void;
        rotate(arg0: number, arg1: number): void;
        getDeterminant(): number;
        getScaleX(): number;
        getShearX(): number;
        getShearY(): number;
        getScaleY(): number;
        translate(arg0: number, arg1: number): void;
        preConcatenate(arg0: $AffineTransform): void;
        invert(): void;
        setTransform(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number): void;
        setTransform(arg0: $AffineTransform): void;
        setToTranslation(arg0: number, arg1: number): void;
        setToRotation(arg0: number): void;
        setToRotation(arg0: number, arg1: number): void;
        setToRotation(arg0: number, arg1: number, arg2: number, arg3: number): void;
        setToRotation(arg0: number, arg1: number, arg2: number): void;
        setToQuadrantRotation(arg0: number): void;
        setToQuadrantRotation(arg0: number, arg1: number, arg2: number): void;
        setToScale(arg0: number, arg1: number): void;
        setToShear(arg0: number, arg1: number): void;
        static getRotateInstance(arg0: number, arg1: number, arg2: number): $AffineTransform;
        static getRotateInstance(arg0: number): $AffineTransform;
        static getRotateInstance(arg0: number, arg1: number, arg2: number, arg3: number): $AffineTransform;
        static getRotateInstance(arg0: number, arg1: number): $AffineTransform;
        static getQuadrantRotateInstance(arg0: number, arg1: number, arg2: number): $AffineTransform;
        static getQuadrantRotateInstance(arg0: number): $AffineTransform;
        static getScaleInstance(arg0: number, arg1: number): $AffineTransform;
        static getShearInstance(arg0: number, arg1: number): $AffineTransform;
        quadrantRotate(arg0: number, arg1: number, arg2: number): void;
        quadrantRotate(arg0: number): void;
        setToIdentity(): void;
        inverseTransform(arg0: $Point2D, arg1: $Point2D): $Point2D;
        inverseTransform(arg0: number[], arg1: number, arg2: number[], arg3: number, arg4: number): void;
        createTransformedShape(arg0: $Shape): $Shape;
        getTranslateX(): number;
        getTranslateY(): number;
        deltaTransform(arg0: $Point2D, arg1: $Point2D): $Point2D;
        deltaTransform(arg0: number[], arg1: number, arg2: number[], arg3: number, arg4: number): void;
        concatenate(arg0: $AffineTransform): void;
        createInverse(): $AffineTransform;
        static getTranslateInstance(arg0: number, arg1: number): $AffineTransform;
        getMatrix(arg0: number[]): void;
        shear(arg0: number, arg1: number): void;
        static TYPE_QUADRANT_ROTATION: number;
        static TYPE_TRANSLATION: number;
        static TYPE_IDENTITY: number;
        static TYPE_UNIFORM_SCALE: number;
        static TYPE_MASK_SCALE: number;
        static TYPE_MASK_ROTATION: number;
        static TYPE_GENERAL_SCALE: number;
        static TYPE_FLIP: number;
        static TYPE_GENERAL_ROTATION: number;
        static TYPE_GENERAL_TRANSFORM: number;
        constructor(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number);
        constructor(arg0: number[]);
        constructor(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number);
        constructor(arg0: number[]);
        constructor();
        constructor(arg0: $AffineTransform);
        get type(): number;
        get identity(): boolean;
        get determinant(): number;
        get scaleX(): number;
        get shearX(): number;
        get shearY(): number;
        get scaleY(): number;
        get translateX(): number;
        get translateY(): number;
    }
    export class $Dimension2D implements $Cloneable {
        clone(): $Object;
        setSize(arg0: number, arg1: number): void;
        setSize(arg0: $Dimension2D): void;
        getWidth(): number;
        getHeight(): number;
        get width(): number;
        get height(): number;
    }
    export class $Rectangle2D extends $RectangularShape {
        add(arg0: $Rectangle2D): void;
        add(arg0: number, arg1: number): void;
        add(arg0: $Point2D): void;
        static union(arg0: $Rectangle2D, arg1: $Rectangle2D, arg2: $Rectangle2D): void;
        static intersect(arg0: $Rectangle2D, arg1: $Rectangle2D, arg2: $Rectangle2D): void;
        setRect(arg0: number, arg1: number, arg2: number, arg3: number): void;
        setRect(arg0: $Rectangle2D): void;
        outcode(arg0: $Point2D): number;
        outcode(arg0: number, arg1: number): number;
        createIntersection(arg0: $Rectangle2D): $Rectangle2D;
        createUnion(arg0: $Rectangle2D): $Rectangle2D;
        intersectsLine(arg0: number, arg1: number, arg2: number, arg3: number): boolean;
        intersectsLine(arg0: $Line2D): boolean;
        static OUT_TOP: number;
        static OUT_RIGHT: number;
        static OUT_BOTTOM: number;
        static OUT_LEFT: number;
    }
    export class $Point2D implements $Cloneable {
        clone(): $Object;
        distance(arg0: number, arg1: number): number;
        distance(arg0: $Point2D): number;
        static distance(arg0: number, arg1: number, arg2: number, arg3: number): number;
        setLocation(arg0: number, arg1: number): void;
        setLocation(arg0: $Point2D): void;
        getX(): number;
        getY(): number;
        distanceSq(arg0: number, arg1: number): number;
        distanceSq(arg0: $Point2D): number;
        static distanceSq(arg0: number, arg1: number, arg2: number, arg3: number): number;
        get x(): number;
        get y(): number;
    }
    export class $PathIterator {
        static WIND_EVEN_ODD: number;
        static SEG_QUADTO: number;
        static SEG_CLOSE: number;
        static SEG_CUBICTO: number;
        static SEG_LINETO: number;
        static WIND_NON_ZERO: number;
        static SEG_MOVETO: number;
    }
    export interface $PathIterator {
        next(): void;
        isDone(): boolean;
        currentSegment(arg0: number[]): number;
        currentSegment(arg0: number[]): number;
        getWindingRule(): number;
        get done(): boolean;
        get windingRule(): number;
    }
    export class $RectangularShape implements $Shape, $Cloneable {
        clone(): $Object;
        isEmpty(): boolean;
        contains(arg0: $Rectangle2D): boolean;
        contains(arg0: $Point2D): boolean;
        getBounds(): $Rectangle;
        intersects(arg0: $Rectangle2D): boolean;
        getWidth(): number;
        getHeight(): number;
        getMinX(): number;
        getMinY(): number;
        getPathIterator(arg0: $AffineTransform, arg1: number): $PathIterator;
        getX(): number;
        getCenterY(): number;
        getMaxX(): number;
        getY(): number;
        getMaxY(): number;
        setFrame(arg0: number, arg1: number, arg2: number, arg3: number): void;
        setFrame(arg0: $Rectangle2D): void;
        setFrame(arg0: $Point2D, arg1: $Dimension2D): void;
        setFrameFromDiagonal(arg0: number, arg1: number, arg2: number, arg3: number): void;
        setFrameFromDiagonal(arg0: $Point2D, arg1: $Point2D): void;
        setFrameFromCenter(arg0: number, arg1: number, arg2: number, arg3: number): void;
        setFrameFromCenter(arg0: $Point2D, arg1: $Point2D): void;
        getCenterX(): number;
        getFrame(): $Rectangle2D;
        get empty(): boolean;
        get bounds(): $Rectangle;
        get width(): number;
        get height(): number;
        get minX(): number;
        get minY(): number;
        get x(): number;
        get centerY(): number;
        get maxX(): number;
        get y(): number;
        get maxY(): number;
        get centerX(): number;
    }
}
