import { $JsonObject_ } from "@package/com/google/gson";
import { $NumberProvider_ } from "@package/net/minecraft/world/level/storage/loot/providers/number";
import { $Ingredient_ } from "@package/net/minecraft/world/item/crafting";
import { $CompoundTag_ } from "@package/net/minecraft/nbt";
import { $EquipmentSlot_, $Entity } from "@package/net/minecraft/world/entity";
import { $LootItem, $LootPoolEntryType, $NestedLootTable, $TagEntry, $EmptyLootItem, $CompositeEntryBase, $LootPoolSingletonContainer, $LootPoolEntryContainer } from "@package/net/minecraft/world/level/storage/loot/entries";
import { $List, $Map_ } from "@package/java/util";
import { $LootFunctionsContainer, $LootConditionsContainer, $LootEntryList, $LootFunctionList, $LootConditionList, $AddAttributesFunction$Builder } from "@package/com/almostreliable/lootjs/loot";
import { $Consumer_, $UnaryOperator_, $Predicate_ } from "@package/java/util/function";
import { $ServerPlayer } from "@package/net/minecraft/server/level";
import { $Holder_, $HolderSet_, $BlockPos_ } from "@package/net/minecraft/core";
import { $Enchantment } from "@package/net/minecraft/world/item/enchantment";
import { $IdFilter_, $ItemFilter_ } from "@package/com/almostreliable/lootjs/core/filters";
import { $Structure } from "@package/net/minecraft/world/level/levelgen/structure";
import { $LootContext } from "@package/net/minecraft/world/level/storage/loot";
import { $TagKey_ } from "@package/net/minecraft/tags";
import { $Item_, $Item, $ItemStack_, $ItemStack } from "@package/net/minecraft/world/item";
import { $Component_ } from "@package/net/minecraft/network/chat";
import { $Biome } from "@package/net/minecraft/world/level/biome";
import { $SetEnchantmentsFunction$Builder, $LootItemFunction } from "@package/net/minecraft/world/level/storage/loot/functions";
import { $DistancePredicate_, $StatePropertiesPredicate_, $DamageSourcePredicate_, $ItemPredicate_, $EntityPredicate_, $MinMaxBounds$Doubles_, $LocationPredicate_, $EntityPredicate } from "@package/net/minecraft/advancements/critereon";
import { $Potion_ } from "@package/net/minecraft/world/item/alchemy";
import { $ResourceLocation_, $ResourceLocation } from "@package/net/minecraft/resources";
import { $LootItemCondition } from "@package/net/minecraft/world/level/storage/loot/predicates";
import { $Block_ } from "@package/net/minecraft/world/level/block";
import { $DebugInfo } from "@package/com/almostreliable/lootjs/util";
import { $LootEntryAppender, $LootEntriesTransformer } from "@package/com/almostreliable/lootjs/loot/table";
import { $BlockEntity } from "@package/net/minecraft/world/level/block/entity";

declare module "@package/com/almostreliable/lootjs/core/entry" {
    export class $TagLootEntry extends $AbstractSimpleLootEntry<$TagEntry> implements $SingleLootEntry {
        getTag(): string;
        isTag(arg0: string): boolean;
        setTag(arg0: string): void;
        getExpand(): boolean;
        setExpand(arg0: boolean): void;
        when(arg0: $Consumer_<$LootConditionList>): $LootEntry;
        addFunction(arg0: $LootItemFunction): $SimpleLootEntry;
        constructor(arg0: $TagEntry);
        constructor(arg0: $TagKey_<$Item>, arg1: boolean);
    }
    export class $TableReferenceLootEntry extends $AbstractSimpleLootEntry<$NestedLootTable> {
        getLocation(): $ResourceLocation;
        setLocation(arg0: $ResourceLocation_): void;
        addCondition(arg0: $LootItemCondition): $TableReferenceLootEntry;
        when(arg0: $Consumer_<$LootConditionList>): $LootEntry;
        addFunction(arg0: $LootItemFunction): $SimpleLootEntry;
        constructor(arg0: $NestedLootTable);
        constructor(arg0: $ResourceLocation_);
    }
    export class $AbstractSimpleLootEntry<E extends $LootPoolSingletonContainer> implements $SimpleLootEntry {
        getFunctions(): $LootFunctionList;
        setWeight(arg0: number): void;
        setQuality(arg0: number): void;
        getWeight(): number;
        getConditions(): $LootConditionList;
        collectDebugInfo(arg0: $DebugInfo): void;
        getQuality(): number;
        getVanillaType(): $LootPoolEntryType;
        getVanillaEntry(): E;
        apply(arg0: $Consumer_<$LootFunctionList>): $SimpleLootEntry;
        setCount(arg0: $NumberProvider_): $SimpleLootEntry;
        withWeight(arg0: number): $SimpleLootEntry;
        withQuality(arg0: number): $SimpleLootEntry;
        isEmpty(): boolean;
        getType(): $ResourceLocation;
        isDynamic(): boolean;
        isSimple(): boolean;
        isReference(): boolean;
        isTag(): boolean;
        isItem(): boolean;
        isComposite(): boolean;
        createRandomItem(arg0: $LootContext): $ItemStack;
        isAlternative(): boolean;
        isGroup(): boolean;
        isSequence(): boolean;
        setName(arg0: $Component_): $SimpleLootEntry;
        addAttributes(arg0: $Consumer_<$AddAttributesFunction$Builder>): $SimpleLootEntry;
        limitCount(arg0: $NumberProvider_ | null, arg1: $NumberProvider_ | null): $SimpleLootEntry;
        applyBonus(arg0: $Holder_<$Enchantment>, arg1: number): $SimpleLootEntry;
        addLore(...arg0: $Component_[]): $SimpleLootEntry;
        enchant(arg0: boolean, arg1: $Consumer_<$SetEnchantmentsFunction$Builder>): $SimpleLootEntry;
        enchant(arg0: $Consumer_<$SetEnchantmentsFunction$Builder>): $SimpleLootEntry;
        addPotion(arg0: $Potion_): $SimpleLootEntry;
        damage(arg0: $NumberProvider_): $SimpleLootEntry;
        enchantWithLevels(arg0: $NumberProvider_): $SimpleLootEntry;
        setCustomData(arg0: $CompoundTag_): $SimpleLootEntry;
        smelt(): $SimpleLootEntry;
        enchantRandomly(arg0: $HolderSet_<$Enchantment>): $SimpleLootEntry;
        enchantRandomly(): $SimpleLootEntry;
        jsonFunction(arg0: $JsonObject_): $SimpleLootEntry;
        replaceLore(...arg0: $Component_[]): $SimpleLootEntry;
        applyOreBonus(arg0: $Holder_<$Enchantment>): $SimpleLootEntry;
        toggleTooltips(arg0: $Map_<string, boolean>): $SimpleLootEntry;
        applyEnchantmentBonus(arg0: $Holder_<$Enchantment>, arg1: $NumberProvider_): $SimpleLootEntry;
        applyEnchantmentBonus(arg0: $NumberProvider_): $SimpleLootEntry;
        simulateExplosionDecay(): $SimpleLootEntry;
        applyBinomialDistributionBonus(arg0: $Holder_<$Enchantment>, arg1: number, arg2: number): $SimpleLootEntry;
        matchLocation(arg0: $LocationPredicate_): $LootEntry;
        matchLocation(arg0: $BlockPos_, arg1: $LocationPredicate_): $LootEntry;
        blockEntity(arg0: $Predicate_<$BlockEntity>): $LootEntry;
        survivesExplosion(): $LootEntry;
        killedByPlayer(): $LootEntry;
        randomChance(arg0: $NumberProvider_): $LootEntry;
        matchTool(arg0: $ItemPredicate_): $LootEntry;
        luck(arg0: $MinMaxBounds$Doubles_): $LootEntry;
        randomChanceWithEnchantment(arg0: $Holder_<$Enchantment>, arg1: number[]): $LootEntry;
        matchAnyInventorySlot(arg0: $ItemFilter_): $LootEntry;
        matchCustomCondition(arg0: $JsonObject_): $LootEntry;
        matchDirectAttacker(arg0: $EntityPredicate_): $LootEntry;
        matchAttackerCustom(arg0: $Predicate_<$Entity>): $LootEntry;
        matchDirectAttackerCustom(arg0: $Predicate_<$Entity>): $LootEntry;
        isLightLevel(arg0: number, arg1: number): $LootEntry;
        matchPlayerCustom(arg0: $Predicate_<$ServerPlayer>): $LootEntry;
        matchAttacker(arg0: $EntityPredicate_): $LootEntry;
        matchPlayer(arg0: $EntityPredicate_): $LootEntry;
        matchStructure(arg0: $HolderSet_<$Structure>, arg1: boolean): $LootEntry;
        matchStructure(arg0: $HolderSet_<$Structure>): $LootEntry;
        matchWeather(arg0: boolean | null, arg1: boolean | null): $LootEntry;
        hasAnyStage(...arg0: string[]): $LootEntry;
        matchAnyHotbarSlot(arg0: $ItemFilter_): $LootEntry;
        matchDimension(...arg0: $ResourceLocation_[]): $LootEntry;
        matchEntityCustom(arg0: $Predicate_<$Entity>): $LootEntry;
        matchMainHand(arg0: $ItemFilter_): $LootEntry;
        matchOffHand(arg0: $ItemFilter_): $LootEntry;
        randomTableBonus(arg0: $Holder_<$Enchantment>, arg1: number[]): $LootEntry;
        matchDamageSource(arg0: $DamageSourcePredicate_): $LootEntry;
        matchDistance(arg0: $DistancePredicate_): $LootEntry;
        matchEntity(arg0: $EntityPredicate_): $LootEntry;
        matchAnyOf(...arg0: $LootItemCondition[]): $LootEntry;
        matchChest(arg0: $ItemFilter_): $LootEntry;
        matchBiome(arg0: $HolderSet_<$Biome>): $LootEntry;
        matchHead(arg0: $ItemFilter_): $LootEntry;
        matchLegs(arg0: $ItemFilter_): $LootEntry;
        matchBlock(arg0: $Block_): $LootEntry;
        matchBlock(arg0: $Block_, arg1: $StatePropertiesPredicate_): $LootEntry;
        matchFeet(arg0: $ItemFilter_): $LootEntry;
        matchAllOf(...arg0: $LootItemCondition[]): $LootEntry;
        matchEquip(arg0: $EquipmentSlot_, arg1: $ItemFilter_): $LootEntry;
        matchTime(arg0: number, arg1: number): $LootEntry;
        matchTime(arg0: number, arg1: number, arg2: number): $LootEntry;
        when(arg0: $Consumer_<$LootConditionList>): $LootEntry;
        addFunction(arg0: $LootItemFunction): $SimpleLootEntry;
        constructor(arg0: E);
        constructor(arg0: E, arg1: $LootConditionList, arg2: $LootFunctionList);
        get functions(): $LootFunctionList;
        get conditions(): $LootConditionList;
        get vanillaType(): $LootPoolEntryType;
        get vanillaEntry(): E;
        set count(value: $NumberProvider_);
        get type(): $ResourceLocation;
        get dynamic(): boolean;
        get simple(): boolean;
        get item(): boolean;
        get composite(): boolean;
        set name(value: $Component_);
        set customData(value: $CompoundTag_);
    }
    export class $SingleLootEntry {
    }
    export interface $SingleLootEntry extends $SimpleLootEntry {
    }
    export class $SimpleLootEntry {
    }
    export interface $SimpleLootEntry extends $LootEntry, $LootFunctionsContainer<$SimpleLootEntry> {
        apply(arg0: $Consumer_<$LootFunctionList>): $SimpleLootEntry;
        setCount(arg0: $NumberProvider_): $SimpleLootEntry;
        getFunctions(): $LootFunctionList;
        setWeight(arg0: number): void;
        setQuality(arg0: number): void;
        getWeight(): number;
        withWeight(arg0: number): $SimpleLootEntry;
        getQuality(): number;
        withQuality(arg0: number): $SimpleLootEntry;
        when(arg0: $Consumer_<$LootConditionList>): $LootEntry;
        addFunction(arg0: $LootItemFunction): $SimpleLootEntry;
        set count(value: $NumberProvider_);
        get functions(): $LootFunctionList;
    }
    export class $ItemLootEntry extends $AbstractSimpleLootEntry<$LootItem> implements $SingleLootEntry {
        test(arg0: $ItemFilter_): boolean;
        getItem(): $Item;
        setItem(arg0: $Item_): void;
        when(arg0: $Consumer_<$LootConditionList>): $LootEntry;
        addFunction(arg0: $LootItemFunction): $SimpleLootEntry;
        constructor(arg0: $Item_, arg1: $NumberProvider_ | null);
        constructor(arg0: $ItemStack_);
        constructor(arg0: $LootItem);
    }
    export class $LootEntry {
        static group(...arg0: $LootEntry[]): $CompositeLootEntry;
        static of(arg0: $Item_, arg1: $NumberProvider_): $ItemLootEntry;
        static of(arg0: $ItemStack_): $ItemLootEntry;
        static empty(): $EmptyLootEntry;
        static reference(arg0: $ResourceLocation_): $TableReferenceLootEntry;
        static sequence(...arg0: $LootEntry[]): $CompositeLootEntry;
        static tag(arg0: string, arg1: boolean): $TagLootEntry;
        static tag(arg0: string): $TagLootEntry;
        static alternative(...arg0: $LootEntry[]): $CompositeLootEntry;
        static testItem(arg0: string): $ItemLootEntry;
        static ofIngredient(arg0: $Ingredient_): $CompositeLootEntry;
        static ep(arg0: $EntityPredicate_): $EntityPredicate;
        static ofItem(arg0: $Item_): $ItemLootEntry;
        static ofVanilla(arg0: $LootPoolEntryContainer): $LootEntry;
        static EMPTY_CONDITIONS: $List<$LootItemCondition>;
        static EMPTY_FUNCTIONS: $List<$LootItemFunction>;
    }
    export interface $LootEntry extends $LootConditionsContainer<$LootEntry> {
        isEmpty(): boolean;
        getType(): $ResourceLocation;
        when(arg0: $Consumer_<$LootConditionList>): $LootEntry;
        isDynamic(): boolean;
        isSimple(): boolean;
        isReference(): boolean;
        getConditions(): $LootConditionList;
        isTag(): boolean;
        collectDebugInfo(arg0: $DebugInfo): void;
        isItem(): boolean;
        isComposite(): boolean;
        createRandomItem(arg0: $LootContext): $ItemStack;
        getVanillaType(): $LootPoolEntryType;
        getVanillaEntry(): $LootPoolEntryContainer;
        isAlternative(): boolean;
        isGroup(): boolean;
        isSequence(): boolean;
        get type(): $ResourceLocation;
        get dynamic(): boolean;
        get simple(): boolean;
        get conditions(): $LootConditionList;
        get item(): boolean;
        get composite(): boolean;
        get vanillaType(): $LootPoolEntryType;
        get vanillaEntry(): $LootPoolEntryContainer;
    }
    export class $CompositeLootEntry implements $LootEntry, $LootEntriesTransformer, $LootEntryAppender {
        entries(arg0: $Consumer_<$LootEntryList>): $CompositeLootEntry;
        getEntries(): $LootEntryList;
        removeEntry(arg0: $Predicate_<$SimpleLootEntry>, arg1: boolean): $CompositeLootEntry;
        getConditions(): $LootConditionList;
        collectDebugInfo(arg0: $DebugInfo): void;
        getVanillaType(): $LootPoolEntryType;
        getVanillaEntry(): $CompositeEntryBase;
        isEmpty(): boolean;
        getType(): $ResourceLocation;
        isDynamic(): boolean;
        isSimple(): boolean;
        isReference(): boolean;
        isTag(): boolean;
        isItem(): boolean;
        isComposite(): boolean;
        createRandomItem(arg0: $LootContext): $ItemStack;
        isAlternative(): boolean;
        isGroup(): boolean;
        isSequence(): boolean;
        removeReference(arg0: $IdFilter_, arg1: boolean): $LootEntriesTransformer;
        removeReference(arg0: $IdFilter_): $LootEntriesTransformer;
        removeEntry(arg0: $Predicate_<$SimpleLootEntry>): $LootEntriesTransformer;
        hasItem(arg0: $ItemFilter_): boolean;
        removeItem(arg0: $ItemFilter_): $LootEntriesTransformer;
        removeItem(arg0: $ItemFilter_, arg1: boolean): $LootEntriesTransformer;
        removeTag(arg0: string, arg1: boolean): $LootEntriesTransformer;
        removeTag(arg0: string): $LootEntriesTransformer;
        replaceItem(arg0: $ItemFilter_, arg1: $Item_): $LootEntriesTransformer;
        replaceItem(arg0: $ItemFilter_, arg1: $Item_, arg2: boolean): $LootEntriesTransformer;
        modifyItemEntry(arg0: $UnaryOperator_<$ItemLootEntry>): $LootEntriesTransformer;
        modifyEntry(arg0: $UnaryOperator_<$SimpleLootEntry>): $LootEntriesTransformer;
        addCustomEntry(arg0: $JsonObject_): $LootEntryAppender;
        matchLocation(arg0: $LocationPredicate_): $LootEntry;
        matchLocation(arg0: $BlockPos_, arg1: $LocationPredicate_): $LootEntry;
        blockEntity(arg0: $Predicate_<$BlockEntity>): $LootEntry;
        survivesExplosion(): $LootEntry;
        killedByPlayer(): $LootEntry;
        randomChance(arg0: $NumberProvider_): $LootEntry;
        matchTool(arg0: $ItemPredicate_): $LootEntry;
        luck(arg0: $MinMaxBounds$Doubles_): $LootEntry;
        randomChanceWithEnchantment(arg0: $Holder_<$Enchantment>, arg1: number[]): $LootEntry;
        matchAnyInventorySlot(arg0: $ItemFilter_): $LootEntry;
        matchCustomCondition(arg0: $JsonObject_): $LootEntry;
        matchDirectAttacker(arg0: $EntityPredicate_): $LootEntry;
        matchAttackerCustom(arg0: $Predicate_<$Entity>): $LootEntry;
        matchDirectAttackerCustom(arg0: $Predicate_<$Entity>): $LootEntry;
        isLightLevel(arg0: number, arg1: number): $LootEntry;
        matchPlayerCustom(arg0: $Predicate_<$ServerPlayer>): $LootEntry;
        matchAttacker(arg0: $EntityPredicate_): $LootEntry;
        matchPlayer(arg0: $EntityPredicate_): $LootEntry;
        matchStructure(arg0: $HolderSet_<$Structure>, arg1: boolean): $LootEntry;
        matchStructure(arg0: $HolderSet_<$Structure>): $LootEntry;
        matchWeather(arg0: boolean | null, arg1: boolean | null): $LootEntry;
        hasAnyStage(...arg0: string[]): $LootEntry;
        matchAnyHotbarSlot(arg0: $ItemFilter_): $LootEntry;
        matchDimension(...arg0: $ResourceLocation_[]): $LootEntry;
        matchEntityCustom(arg0: $Predicate_<$Entity>): $LootEntry;
        matchMainHand(arg0: $ItemFilter_): $LootEntry;
        matchOffHand(arg0: $ItemFilter_): $LootEntry;
        randomTableBonus(arg0: $Holder_<$Enchantment>, arg1: number[]): $LootEntry;
        matchDamageSource(arg0: $DamageSourcePredicate_): $LootEntry;
        matchDistance(arg0: $DistancePredicate_): $LootEntry;
        matchEntity(arg0: $EntityPredicate_): $LootEntry;
        matchAnyOf(...arg0: $LootItemCondition[]): $LootEntry;
        matchChest(arg0: $ItemFilter_): $LootEntry;
        matchBiome(arg0: $HolderSet_<$Biome>): $LootEntry;
        matchHead(arg0: $ItemFilter_): $LootEntry;
        matchLegs(arg0: $ItemFilter_): $LootEntry;
        matchBlock(arg0: $Block_): $LootEntry;
        matchBlock(arg0: $Block_, arg1: $StatePropertiesPredicate_): $LootEntry;
        matchFeet(arg0: $ItemFilter_): $LootEntry;
        matchAllOf(...arg0: $LootItemCondition[]): $LootEntry;
        matchEquip(arg0: $EquipmentSlot_, arg1: $ItemFilter_): $LootEntry;
        matchTime(arg0: number, arg1: number): $LootEntry;
        matchTime(arg0: number, arg1: number, arg2: number): $LootEntry;
        addEntry(arg0: $LootEntry): $LootEntryAppender;
        when(arg0: $Consumer_<$LootConditionList>): $LootEntry;
        addCondition(arg0: $LootItemCondition): $LootEntry;
        modifyEntry(arg0: $UnaryOperator_<$SimpleLootEntry>, arg1: boolean): $LootEntriesTransformer;
        constructor(arg0: $CompositeEntryBase);
        constructor(arg0: $CompositeEntryBase, arg1: $LootEntryList, arg2: $LootConditionList);
        get conditions(): $LootConditionList;
        get vanillaType(): $LootPoolEntryType;
        get vanillaEntry(): $CompositeEntryBase;
        get type(): $ResourceLocation;
        get dynamic(): boolean;
        get simple(): boolean;
        get item(): boolean;
        get composite(): boolean;
    }
    export class $EmptyLootEntry extends $AbstractSimpleLootEntry<$EmptyLootItem> implements $SingleLootEntry {
        addCondition(arg0: $LootItemCondition): $EmptyLootEntry;
        when(arg0: $Consumer_<$LootConditionList>): $LootEntry;
        addFunction(arg0: $LootItemFunction): $SimpleLootEntry;
        constructor(arg0: $EmptyLootItem);
        constructor();
    }
}
