import { $Level, $Level_ } from "@package/net/minecraft/world/level";
import { $ParticlePayload$EffectType_ } from "@package/dev/shadowsoffire/gateways/payloads";
import { $ItemStack_ } from "@package/net/minecraft/world/item";
import { $CompoundTag } from "@package/net/minecraft/nbt";
import { $Component } from "@package/net/minecraft/network/chat";
import { $IEntityWithComplexSpawn } from "@package/net/neoforged/neoforge/entity";
import { $EntityDimensions, $EntityType_, $Entity$RemovalReason, $LivingEntity, $PortalProcessor, $Entity } from "@package/net/minecraft/world/entity";
import { $Player } from "@package/net/minecraft/world/entity/player";
import { $Stack, $Collection_ } from "@package/java/util";
import { $Wave, $Gateway } from "@package/dev/shadowsoffire/gateways/gate";
import { $EntityDataAccessor } from "@package/net/minecraft/network/syncher";
import { $ServerBossEvent } from "@package/net/minecraft/server/level";
import { $HolderLookup$Provider, $BlockPos } from "@package/net/minecraft/core";
import { $RegistryFriendlyByteBuf } from "@package/net/minecraft/network";
import { $DynamicHolder } from "@package/dev/shadowsoffire/placebo/reload";
import { $Enum } from "@package/java/lang";
import { $Vec3 } from "@package/net/minecraft/world/phys";

declare module "@package/dev/shadowsoffire/gateways/entity" {
    export class $GatewayEntity$FailureReason extends $Enum<$GatewayEntity$FailureReason> {
        static values(): $GatewayEntity$FailureReason[];
        static valueOf(arg0: string): $GatewayEntity$FailureReason;
        getMsg(): $Component;
        static ENTITY_DISCARDED: $GatewayEntity$FailureReason;
        static ENTITY_TOO_FAR: $GatewayEntity$FailureReason;
        static NO_NEARBY_PLAYER: $GatewayEntity$FailureReason;
        static SPAWN_FAILED: $GatewayEntity$FailureReason;
        static TIMER_ELAPSED: $GatewayEntity$FailureReason;
        static OUT_OF_LIVES: $GatewayEntity$FailureReason;
        static ENTITY_LEFT_DIMENSION: $GatewayEntity$FailureReason;
        get msg(): $Component;
    }
    /**
     * Values that may be interpreted as {@link $GatewayEntity$FailureReason}.
     */
    export type $GatewayEntity$FailureReason_ = "spawn_failed" | "entity_too_far" | "timer_elapsed" | "entity_discarded" | "entity_left_dimension" | "no_nearby_player" | "out_of_lives";
    export class $GatewayEntity extends $Entity implements $IEntityWithComplexSpawn {
        static getOwner(arg0: $Entity): $GatewayEntity;
        isCompleted(): boolean;
        isValid(): boolean;
        getGateway(): $Gateway;
        readSpawnData(arg0: $RegistryFriendlyByteBuf): void;
        writeSpawnData(arg0: $RegistryFriendlyByteBuf): void;
        summonerOrClosest(): $Player;
        static hasLeftDimension(arg0: $Entity): boolean;
        isOutOfRange(arg0: $Entity): boolean;
        static spawnLightningOn(arg0: $Entity, arg1: boolean): void;
        getRemainingLives(): number;
        setRemainingLives(arg0: number): void;
        respawnEntity(arg0: $Entity): boolean;
        getActiveEnemies(): number;
        getClientScale(): number;
        getBossEvent(): $ServerBossEvent;
        setClientScale(arg0: number): void;
        getFailureReason(): $GatewayEntity$FailureReason;
        getWave(): number;
        onFailure(arg0: $Collection_<$LivingEntity>, arg1: $GatewayEntity$FailureReason_): void;
        spawnCompletionItem(arg0: $ItemStack_): void;
        playerDied(arg0: $Player): void;
        handleConversion(arg0: $Entity, arg1: $LivingEntity): void;
        spawnParticle(arg0: number, arg1: number, arg2: number, arg3: $ParticlePayload$EffectType_): void;
        getTicksActive(): number;
        getSetupTime(): number;
        getCurrentWave(): $Wave;
        isWaveActive(): boolean;
        getMaxWaveTime(): number;
        spawnItem(arg0: $ItemStack_): void;
        onGateCreated(): void;
        serializeNBT(arg0: $HolderLookup$Provider): $CompoundTag;
        xRot: number;
        hasImpulse: boolean;
        ars_Nouveau$motions: $Stack<any>;
        stuckSpeedMultiplier: $Vec3;
        tickCount: number;
        an_isRewinding: boolean;
        noPhysics: boolean;
        yo: number;
        static ENEMIES: $EntityDataAccessor<number>;
        static BOARDING_COOLDOWN: number;
        removalReason: $Entity$RemovalReason;
        yRotO: number;
        static CONTENTS_SLOT_INDEX: number;
        level: $Level;
        yRot: number;
        moveDist: number;
        static ID_TAG: string;
        mainSupportingBlockPos: ($BlockPos) | undefined;
        static DELTA_AFFECTED_BY_BLOCKS_BELOW_1_0: number;
        xRotO: number;
        static WAVE_ACTIVE: $EntityDataAccessor<boolean>;
        zo: number;
        create_diesel_generators$turretPos: $BlockPos;
        walkDist: number;
        xOld: number;
        noCulling: boolean;
        wasInPowderSnow: boolean;
        hurtMarked: boolean;
        invulnerableTime: number;
        static UUID_TAG: string;
        static BASE_TICKS_REQUIRED_TO_FREEZE: number;
        fallDistance: number;
        static HAS_NEARBY_PLAYER: $EntityDataAccessor<boolean>;
        portalProcess: $PortalProcessor;
        verticalCollision: boolean;
        static DELTA_AFFECTED_BY_BLOCKS_BELOW_0_5: number;
        static MAX_ENTITY_TAG_COUNT: number;
        static DELTA_AFFECTED_BY_BLOCKS_BELOW_0_2: number;
        verticalCollisionBelow: boolean;
        static WAVE: $EntityDataAccessor<number>;
        yOld: number;
        static DEFAULT_BB_WIDTH: number;
        eyeHeight: number;
        minorHorizontalCollision: boolean;
        static DEFAULT_BB_HEIGHT: number;
        static LIVES_REMAINING: $EntityDataAccessor<number>;
        walkDistO: number;
        static FREEZE_HURT_FREQUENCY: number;
        flyDist: number;
        isInPowderSnow: boolean;
        static ATTACHMENTS_NBT_KEY: string;
        static PASSENGERS_TAG: string;
        blocksBuilding: boolean;
        wasOnFire: boolean;
        static TICKS_ACTIVE: $EntityDataAccessor<number>;
        zOld: number;
        static TOTAL_AIR_SUPPLY: number;
        xo: number;
        static BASE_SAFE_FALL_DISTANCE: number;
        wasTouchingWater: boolean;
        horizontalCollision: boolean;
        dimensions: $EntityDimensions;
        constructor(arg0: $EntityType_<$GatewayEntity>, arg1: $Level_, arg2: $Player, arg3: $DynamicHolder<$Gateway>);
        constructor(arg0: $EntityType_<never>, arg1: $Level_);
        get completed(): boolean;
        get valid(): boolean;
        get gateway(): $Gateway;
        get activeEnemies(): number;
        get bossEvent(): $ServerBossEvent;
        get failureReason(): $GatewayEntity$FailureReason;
        get wave(): number;
        get ticksActive(): number;
        get setupTime(): number;
        get currentWave(): $Wave;
        get waveActive(): boolean;
        get maxWaveTime(): number;
    }
}
