import { $Level } from "@package/net/minecraft/world/level";
import { $EnderDragon } from "@package/net/minecraft/world/entity/boss/enderdragon";
import { $HolderLookup$Provider, $BlockPos } from "@package/net/minecraft/core";
import { $PartEntity } from "@package/net/neoforged/neoforge/entity";
import { $Entity$RemovalReason, $EntityDimensions, $PortalProcessor } from "@package/net/minecraft/world/entity";
import { $Stack } from "@package/java/util";
import { $Vec3 } from "@package/net/minecraft/world/phys";
export * as enderdragon from "@package/net/minecraft/world/entity/boss/enderdragon";
export * as wither from "@package/net/minecraft/world/entity/boss/wither";

declare module "@package/net/minecraft/world/entity/boss" {
    export class $EnderDragonPart extends $PartEntity<$EnderDragon> {
        serializeNBT(arg0: $HolderLookup$Provider): $EnderDragon;
        xRot: number;
        hasImpulse: boolean;
        parentMob: $EnderDragon;
        ars_Nouveau$motions: $Stack<any>;
        stuckSpeedMultiplier: $Vec3;
        tickCount: number;
        an_isRewinding: boolean;
        noPhysics: boolean;
        yo: number;
        static BOARDING_COOLDOWN: number;
        removalReason: $Entity$RemovalReason;
        yRotO: number;
        static CONTENTS_SLOT_INDEX: number;
        level: $Level;
        yRot: number;
        moveDist: number;
        static ID_TAG: string;
        mainSupportingBlockPos: ($BlockPos) | undefined;
        static DELTA_AFFECTED_BY_BLOCKS_BELOW_1_0: number;
        xRotO: number;
        zo: number;
        create_diesel_generators$turretPos: $BlockPos;
        walkDist: number;
        name: string;
        xOld: number;
        noCulling: boolean;
        wasInPowderSnow: boolean;
        hurtMarked: boolean;
        invulnerableTime: number;
        static UUID_TAG: string;
        static BASE_TICKS_REQUIRED_TO_FREEZE: number;
        fallDistance: number;
        portalProcess: $PortalProcessor;
        verticalCollision: boolean;
        static DELTA_AFFECTED_BY_BLOCKS_BELOW_0_5: number;
        static MAX_ENTITY_TAG_COUNT: number;
        static DELTA_AFFECTED_BY_BLOCKS_BELOW_0_2: number;
        verticalCollisionBelow: boolean;
        yOld: number;
        static DEFAULT_BB_WIDTH: number;
        eyeHeight: number;
        minorHorizontalCollision: boolean;
        static DEFAULT_BB_HEIGHT: number;
        walkDistO: number;
        static FREEZE_HURT_FREQUENCY: number;
        flyDist: number;
        isInPowderSnow: boolean;
        static ATTACHMENTS_NBT_KEY: string;
        static PASSENGERS_TAG: string;
        blocksBuilding: boolean;
        wasOnFire: boolean;
        zOld: number;
        static TOTAL_AIR_SUPPLY: number;
        xo: number;
        static BASE_SAFE_FALL_DISTANCE: number;
        wasTouchingWater: boolean;
        horizontalCollision: boolean;
        dimensions: $EntityDimensions;
        constructor(parentMob: $EnderDragon, name: string, width: number, height: number);
    }
}
