import { $Level_, $Level } from "@package/net/minecraft/world/level";
import { $ItemStack, $ItemStack_ } from "@package/net/minecraft/world/item";
import { $CompoundTag } from "@package/net/minecraft/nbt";
import { $EntityDimensions, $EntityType_, $Entity$RemovalReason, $Entity, $PortalProcessor } from "@package/net/minecraft/world/entity";
import { $AbstractCatchModifier } from "@package/com/wdiscute/starcatcher/registry/catchmodifiers";
import { $Player } from "@package/net/minecraft/world/entity/player";
import { $UUID, $List, $Stack } from "@package/java/util";
import { $Projectile } from "@package/net/minecraft/world/entity/projectile";
import { $EntityDataAccessor } from "@package/net/minecraft/network/syncher";
import { $HolderLookup$Provider, $BlockPos } from "@package/net/minecraft/core";
import { $ResourceLocation } from "@package/net/minecraft/resources";
import { $FishProperties } from "@package/com/wdiscute/starcatcher/registry";
import { $Vec3 } from "@package/net/minecraft/world/phys";

declare module "@package/com/wdiscute/starcatcher/bobberentity" {
    export class $FishingBobEntity extends $Projectile {
        reel(): void;
        checkBiting(): boolean;
        serializeNBT(arg0: $HolderLookup$Provider): $CompoundTag;
        xRot: number;
        hasImpulse: boolean;
        ars_Nouveau$motions: $Stack<any>;
        ticksInFluid: number;
        stuckSpeedMultiplier: $Vec3;
        tickCount: number;
        an_isRewinding: boolean;
        noPhysics: boolean;
        minTicksToFish: number;
        yo: number;
        leftOwner: boolean;
        maxTicksToFish: number;
        survivesLava: boolean;
        static BOARDING_COOLDOWN: number;
        removalReason: $Entity$RemovalReason;
        yRotO: number;
        static CONTENTS_SLOT_INDEX: number;
        level: $Level;
        yRot: number;
        moveDist: number;
        static ID_TAG: string;
        mainSupportingBlockPos: ($BlockPos) | undefined;
        chanceToFishEachTick: number;
        static DELTA_AFFECTED_BY_BLOCKS_BELOW_1_0: number;
        xRotO: number;
        zo: number;
        create_diesel_generators$turretPos: $BlockPos;
        rlToFish: $ResourceLocation;
        walkDist: number;
        xOld: number;
        noCulling: boolean;
        wasInPowderSnow: boolean;
        static VOID: $EntityDataAccessor<boolean>;
        hurtMarked: boolean;
        invulnerableTime: number;
        static UUID_TAG: string;
        rod: $ItemStack;
        static BASE_TICKS_REQUIRED_TO_FREEZE: number;
        fallDistance: number;
        portalProcess: $PortalProcessor;
        static STATE: $EntityDataAccessor<number>;
        verticalCollision: boolean;
        modifiers: $List<$AbstractCatchModifier>;
        static DELTA_AFFECTED_BY_BLOCKS_BELOW_0_5: number;
        timeBiting: number;
        static MAX_ENTITY_TAG_COUNT: number;
        static DELTA_AFFECTED_BY_BLOCKS_BELOW_0_2: number;
        verticalCollisionBelow: boolean;
        yOld: number;
        static DEFAULT_BB_WIDTH: number;
        eyeHeight: number;
        minorHorizontalCollision: boolean;
        fpToFish: $FishProperties;
        static DEFAULT_BB_HEIGHT: number;
        player: $Player;
        ownerUUID: $UUID;
        walkDistO: number;
        static FREEZE_HURT_FREQUENCY: number;
        flyDist: number;
        isInPowderSnow: boolean;
        static ATTACHMENTS_NBT_KEY: string;
        hasBeenShot: boolean;
        cachedOwner: $Entity;
        static PASSENGERS_TAG: string;
        blocksBuilding: boolean;
        wasOnFire: boolean;
        zOld: number;
        static TOTAL_AIR_SUPPLY: number;
        xo: number;
        static BASE_SAFE_FALL_DISTANCE: number;
        wasTouchingWater: boolean;
        horizontalCollision: boolean;
        dimensions: $EntityDimensions;
        constructor(arg0: $EntityType_<$FishingBobEntity>, arg1: $Level_);
        constructor(arg0: $Level_, arg1: $Player, arg2: $ItemStack_);
    }
}
