import { $UnaryOperator_ } from "@package/java/util/function";
import { $Style } from "@package/net/minecraft/network/chat";
import { $Vec3 } from "@package/net/minecraft/world/phys";
import { $Vector3f } from "@package/org/joml";
import { $Couple } from "@package/net/createmod/catnip/data";

declare module "@package/net/createmod/catnip/theme" {
    export class $Color {
        setValue(arg0: number): $Color;
        copy(): $Color;
        copy(arg0: boolean): $Color;
        getRGB(): number;
        setRed(arg0: number): $Color;
        setRed(arg0: number): $Color;
        setGreen(arg0: number): $Color;
        setGreen(arg0: number): $Color;
        setBlue(arg0: number): $Color;
        setBlue(arg0: number): $Color;
        setAlpha(arg0: number): $Color;
        setAlpha(arg0: number): $Color;
        static rainbowColor(arg0: number): $Color;
        brighter(): $Color;
        darker(): $Color;
        mixWith(arg0: $Color, arg1: number): $Color;
        asVectorF(): $Vector3f;
        asStyle(): $Style;
        scaleAlpha(arg0: number): $Color;
        asVector(): $Vec3;
        getRed(): number;
        getAlpha(): number;
        getBlue(): number;
        getGreen(): number;
        setImmutable(): $Color;
        static mixColors(arg0: $Color, arg1: $Color, arg2: number): $Color;
        static mixColors(arg0: $Couple<$Color>, arg1: number): $Color;
        static mixColors(arg0: number, arg1: number, arg2: number): number;
        getRedAsFloat(): number;
        getAlphaAsFloat(): number;
        ensureMutable(): $Color;
        getBlueAsFloat(): number;
        getGreenAsFloat(): number;
        static generateFromLong(arg0: number): $Color;
        scaleAlphaForText(arg0: number): $Color;
        modifyValue(arg0: $UnaryOperator_<number>): $Color;
        static RED: $Color;
        static TRANSPARENT_BLACK: $Color;
        static WHITE: $Color;
        static BLACK: $Color;
        static SPRING_GREEN: $Color;
        static PURPLE: $Color;
        static GREEN: $Color;
        constructor(arg0: number, arg1: boolean);
        constructor(arg0: number);
        constructor(arg0: number, arg1: number, arg2: number, arg3: number);
        constructor(arg0: number, arg1: number, arg2: number, arg3: number);
        constructor(arg0: number, arg1: number, arg2: number);
        set value(value: number);
        get RGB(): number;
        get redAsFloat(): number;
        get alphaAsFloat(): number;
        get blueAsFloat(): number;
        get greenAsFloat(): number;
    }
}
