import { $TileComponentUpgrade, $ITileComponent, $TileComponentSecurity } from "@package/mekanism/common/tile/component";
import { $CompoundTag, $CompoundTag_ } from "@package/net/minecraft/nbt";
import { $FluidStack_, $FluidStack } from "@package/net/neoforged/neoforge/fluids";
import { $ITileDirectional, $ITileActive, $ITileWrapper, $ITileUpgradable, $IComparatorSupport, $ITileRedstone, $ITileSound, $IRedstoneControl$RedstoneControl, $ITierUpgradable, $ITileRadioactive } from "@package/mekanism/common/tile/interfaces";
import { $LevelBlock } from "@package/dev/latvian/mods/kubejs/level";
import { $ITrackableContainer, $MekanismContainer } from "@package/mekanism/common/inventory/container";
import { $UUID_, $Set, $UUID, $List, $Collection_, $List_ } from "@package/java/util";
import { $AttachedHeat, $AttachedHeat_ } from "@package/mekanism/common/attachments/containers/heat";
import { $ItemPredicate_ } from "@package/dev/latvian/mods/kubejs/item";
import { $Frequency$FrequencyIdentity_, $FrequencyType, $Frequency, $IFrequencyHandler, $TileComponentFrequency } from "@package/mekanism/common/lib/frequency";
import { $IFluidHandler$FluidAction_, $IFluidHandler } from "@package/net/neoforged/neoforge/fluids/capability";
import { $BiFunction_, $Supplier } from "@package/java/util/function";
import { $InteractionResult, $Nameable, $Container } from "@package/net/minecraft/world";
import { $IChemicalHandler, $IChemicalTank, $IMekanismChemicalHandler, $ChemicalStack } from "@package/mekanism/api/chemical";
import { $SoundSource } from "@package/net/minecraft/sounds";
import { $IComputerTile, $BoundMethodHolder } from "@package/mekanism/common/integration/computer";
import { $BlockPos, $GlobalPos, $BlockPos_, $HolderLookup$Provider, $Holder_, $Holder, $Direction_, $Direction } from "@package/net/minecraft/core";
import { $TileEntityTypeRegistryObject } from "@package/mekanism/common/registration/impl";
import { $BlockState_ } from "@package/net/minecraft/world/level/block/state";
import { $RegistryFriendlyByteBuf } from "@package/net/minecraft/network";
import { $ITileHeatHandler } from "@package/mekanism/common/capabilities/heat";
import { $IChemicalTankHolder } from "@package/mekanism/common/capabilities/holder/chemical";
import { $DataComponentType, $DataComponentMap$Builder } from "@package/net/minecraft/core/component";
import { $Level_ } from "@package/net/minecraft/world/level";
import { $IMekanismFluidHandler, $IExtendedFluidTank } from "@package/mekanism/api/fluid";
import { $AttachedChemicals_, $AttachedChemicals } from "@package/mekanism/common/attachments/containers/chemical";
import { $ItemStack_, $ItemStack } from "@package/net/minecraft/world/item";
import { $IUpgradeData } from "@package/mekanism/common/upgrade";
import { $Component_, $Component } from "@package/net/minecraft/network/chat";
import { $IItemHandler } from "@package/net/neoforged/neoforge/items";
import { $Player } from "@package/net/minecraft/world/entity/player";
import { $ClientboundBlockEntityDataPacket } from "@package/net/minecraft/network/protocol/game";
import { $AttachedEnergy_, $AttachedEnergy } from "@package/mekanism/common/attachments/containers/energy";
import { $Chunk3D, $IContentsListener_, $IConfigCardAccess, $Upgrade, $Action_ } from "@package/mekanism/api";
import { $ISecurityTile } from "@package/mekanism/common/lib/security";
import { $SecurityMode } from "@package/mekanism/api/security";
import { $AttachedItems_, $AttachedItems } from "@package/mekanism/common/attachments/containers/item";
import { $IMekanismInventory, $IInventorySlot } from "@package/mekanism/api/inventory";
import { $AttachedFluids_, $AttachedFluids } from "@package/mekanism/common/attachments/containers/fluid";
import { $ICapabilityResolver } from "@package/mekanism/common/capabilities/resolver";
import { $Block, $Block_ } from "@package/net/minecraft/world/level/block";
import { $ContainerType } from "@package/mekanism/common/attachments/containers";
import { $HeatAPI$HeatTransfer, $IHeatCapacitor, $IHeatHandler } from "@package/mekanism/api/heat";
import { $BlockEntity, $BlockEntity$DataComponentInput } from "@package/net/minecraft/world/level/block/entity";
import { $ICapabilityProvider, $BlockCapability } from "@package/net/neoforged/neoforge/capabilities";
import { $IEnergyContainer, $IMekanismStrictEnergyHandler } from "@package/mekanism/api/energy";

declare module "@package/mekanism/common/tile/base" {
    export class $TileEntityUpdateable extends $BlockEntity implements $ITileWrapper {
        isRemote(): boolean;
        sendUpdatePacket(tracking: $BlockEntity): void;
        sendUpdatePacket(): void;
        markDirtyComparator(): void;
        getWorldPositionLong(): number;
        getReducedUpdateTag(provider: $HolderLookup$Provider): $CompoundTag;
        getUpdatePacket(): $ClientboundBlockEntityDataPacket;
        loadAdditional(nbt: $CompoundTag_, provider: $HolderLookup$Provider): void;
        onAdded(): void;
        markForSave(): void;
        getTileGlobalPos(): $GlobalPos;
        getTileChunk(): $Chunk3D;
        getRemapEntries(): $List<$DataComponentType<never>>;
        blockRemoved(): void;
        static ATTACHMENTS_NBT_KEY: string;
        constructor(type: $TileEntityTypeRegistryObject<never>, pos: $BlockPos_, state: $BlockState_);
        get remote(): boolean;
        get worldPositionLong(): number;
        get updatePacket(): $ClientboundBlockEntityDataPacket;
        get tileGlobalPos(): $GlobalPos;
        get tileChunk(): $Chunk3D;
        get remapEntries(): $List<$DataComponentType<never>>;
    }
    export class $TileEntityMekanism extends $CapabilityTileEntity implements $IFrequencyHandler, $ITileDirectional, $IConfigCardAccess, $ITileActive, $ITileSound, $ITileRedstone, $ISecurityTile, $IMekanismInventory, $ITileUpgradable, $ITierUpgradable, $IComparatorSupport, $ITrackableContainer, $IMekanismFluidHandler, $IMekanismStrictEnergyHandler, $ITileHeatHandler, $IMekanismChemicalHandler, $IComputerTile, $ITileRadioactive, $Nameable {
        getName(): $Component;
        close(player: $Player): void;
        open(player: $Player): void;
        getDisplayName(): $Component;
        wasPowered(): boolean;
        getChemicalTanks(side: $Direction_): $List<$IChemicalTank>;
        getEnergyContainers(side: $Direction_): $List<$IEnergyContainer>;
        addComponent(component: $ITileComponent): void;
        getComponent(): $TileComponentUpgrade;
        getCurrentRedstoneLevel(): number;
        getComponents(): $List<$ITileComponent>;
        getComputerName(): string;
        isPowered(): boolean;
        setActive(active: boolean): void;
        setCustomName(name: $Component_): void;
        /**
         * @deprecated
         */
        getLegacyInfuseTanks(): $List<$IChemicalTank>;
        applyInventorySlots(input: $BlockEntity$DataComponentInput, slots: $List_<$IInventorySlot>, attachedItems: $AttachedItems_): void;
        getConfigurationData(provider: $HolderLookup$Provider, player: $Player): $CompoundTag;
        /**
         * @deprecated
         */
        getLegacySlurryTanks(): $List<$IChemicalTank>;
        collectChemicalTanks(builder: $DataComponentMap$Builder, tanks: $List_<$IChemicalTank>): $AttachedChemicals;
        resyncMasterToBounding(): void;
        applyEnergyContainers(input: $BlockEntity$DataComponentInput, containers: $List_<$IEnergyContainer>, attachedEnergy: $AttachedEnergy_): void;
        setConfigurationData(provider: $HolderLookup$Provider, player: $Player, data: $CompoundTag_): void;
        collectHeatCapacitors(builder: $DataComponentMap$Builder, capacitors: $List_<$IHeatCapacitor>): $AttachedHeat;
        configurationDataSet(): void;
        collectEnergyContainers(builder: $DataComponentMap$Builder, containers: $List_<$IEnergyContainer>): $AttachedEnergy;
        collectInventorySlots(builder: $DataComponentMap$Builder, slots: $List_<$IInventorySlot>): $AttachedItems;
        /**
         * @deprecated
         */
        getLegacyPigmentTanks(): $List<$IChemicalTank>;
        addContainerTrackers(container: $MekanismContainer): void;
        getConfigurationDataType(): $Block;
        applyHeatCapacitors(input: $BlockEntity$DataComponentInput, capacitors: $List_<$IHeatCapacitor>, attachedHeat: $AttachedHeat_): void;
        validateSecurityIsPublic(): void;
        getInitialChemicalTanks(listener: $IContentsListener_): $IChemicalTankHolder;
        shouldDumpRadiation(): boolean;
        encodeExtraContainerData(buffer: $RegistryFriendlyByteBuf): void;
        isRedstoneActivated(): boolean;
        getSupportedUpgrade(): $Set<$Upgrade>;
        saveAdditional(nbtTags: $CompoundTag_, provider: $HolderLookup$Provider): void;
        persists(type: $ContainerType<never, never, never>): boolean;
        isActivatable(): boolean;
        getDirection(): $Direction;
        getCustomName(): $Component;
        getBlockHolder(): $Holder<$Block>;
        updatePower(): void;
        getActive(): boolean;
        onNeighborChange(block: $Block_, neighborPos: $BlockPos_): void;
        setFacing(direction: $Direction_, notifyCaps: boolean): void;
        setFacing(direction: $Direction_): void;
        hasGui(): boolean;
        openGui(player: $Player): $InteractionResult;
        isDirectional(): boolean;
        canBeUpgraded(): boolean;
        hasInventory(): boolean;
        getRedstoneLevel(): number;
        recalculateUpgrades(upgrade: $Upgrade): void;
        static tickServer(level: $Level_, pos: $BlockPos_, state: $BlockState_, tile: $TileEntityMekanism): void;
        static tickClient(level: $Level_, pos: $BlockPos_, state: $BlockState_, tile: $TileEntityMekanism): void;
        canHandleFluid(): boolean;
        canHandleHeat(): boolean;
        canHandleChemicals(): boolean;
        insertEnergy(container: number, amount: number, side: $Direction_, action: $Action_): number;
        insertEnergy(amount: number, side: $Direction_, action: $Action_): number;
        canHandleEnergy(): boolean;
        getAdjacent(side: $Direction_): $IHeatHandler;
        getFrequencyComponent(): $TileComponentFrequency;
        supportsUpgrades(): boolean;
        getAmbientTemperature(side: $Direction_): number;
        getHeatCapacitors(side: $Direction_): $List<$IHeatCapacitor>;
        getInventorySlots(side: $Direction_): $List<$IInventorySlot>;
        getFluidTanks(side: $Direction_): $List<$IExtendedFluidTank>;
        hasSound(): boolean;
        syncs(type: $ContainerType<never, never, never>): boolean;
        tryWrench(state: $BlockState_, player: $Player, stack: $ItemStack_): $WrenchResult;
        isNameable(): boolean;
        getComputerMethods(holder: $BoundMethodHolder): void;
        applyChemicalTanks(input: $BlockEntity$DataComponentInput, tanks: $List_<$IChemicalTank>, attachedChemicals: $AttachedChemicals_): void;
        hasComputerSupport(): boolean;
        collectFluidTanks(builder: $DataComponentMap$Builder, tanks: $List_<$IExtendedFluidTank>): $AttachedFluids;
        applyFluidTanks(input: $BlockEntity$DataComponentInput, tanks: $List_<$IExtendedFluidTank>, attachedFluids: $AttachedFluids_): void;
        parseUpgradeData(provider: $HolderLookup$Provider, data: $IUpgradeData): void;
        /**
         * @deprecated
         */
        getLegacyGasTanks(): $List<$IChemicalTank>;
        canFunction(): boolean;
        getInputRate(): number;
        onSecurityChanged(old: $SecurityMode, mode: $SecurityMode): void;
        getSecurity(): $TileComponentSecurity;
        writeSustainedData(provider: $HolderLookup$Provider, data: $CompoundTag_): void;
        readSustainedData(provider: $HolderLookup$Provider, data: $CompoundTag_): void;
        supportsRedstone(): boolean;
        getRadiationScale(): number;
        getControlType(): $IRedstoneControl$RedstoneControl;
        supportsComparator(): boolean;
        setControlType(type: $IRedstoneControl$RedstoneControl): void;
        hasSecurity(): boolean;
        persistsToItem(type: $ContainerType<never, never, never>): boolean;
        onContentsChanged(): void;
        getFrequency<FREQ extends $Frequency>(type: $FrequencyType<FREQ>): FREQ;
        setFrequency(type: $FrequencyType<never>, data: $Frequency$FrequencyIdentity_, player: $UUID_): void;
        getPrivateCache<FREQ extends $Frequency>(type: $FrequencyType<FREQ>): $List<FREQ>;
        removeFrequency(type: $FrequencyType<never>, data: $Frequency$FrequencyIdentity_, player: $UUID_): void;
        getPublicCache<FREQ extends $Frequency>(type: $FrequencyType<FREQ>): $List<FREQ>;
        getTrustedCache<FREQ extends $Frequency>(type: $FrequencyType<FREQ>): $List<FREQ>;
        getOppositeDirection(): $Direction;
        getRightSide(): $Direction;
        getLeftSide(): $Direction;
        getConfigCardName(): string;
        isConfigurationDataCompatible(arg0: $Block_): boolean;
        getVolume(): number;
        getSoundCategory(): $SoundSource;
        getSoundPos(): $BlockPos;
        getInitialVolume(): number;
        supportsMode(mode: $IRedstoneControl$RedstoneControl): boolean;
        onPowerChange(): void;
        getOwnerUUID(): $UUID;
        getOwnerName(): string;
        setOwnerUUID(owner: $UUID_): void;
        setSecurityMode(mode: $SecurityMode): void;
        getSecurityMode(): $SecurityMode;
        getStackInSlot(arg0: number, arg1: $Direction_): $ItemStack;
        insertItem(arg0: number, arg1: $ItemStack_, arg2: $Direction_, arg3: $Action_): $ItemStack;
        getInventorySlot(arg0: number, arg1: $Direction_): $IInventorySlot;
        getSlots(arg0: $Direction_): number;
        extractItem(arg0: number, arg1: number, arg2: $Direction_, arg3: $Action_): $ItemStack;
        setStackInSlot(arg0: number, arg1: $ItemStack_, arg2: $Direction_): void;
        isItemValid(arg0: number, arg1: $ItemStack_, arg2: $Direction_): boolean;
        getSlotLimit(arg0: number, arg1: $Direction_): number;
        isInventoryEmpty(): boolean;
        isInventoryEmpty(arg0: $Direction_): boolean;
        getInfo(upgrade: $Upgrade): $List<$Component>;
        getUpgradeData(provider: $HolderLookup$Provider): $IUpgradeData;
        getTanks(arg0: $Direction_): number;
        getFluidInTank(arg0: number, arg1: $Direction_): $FluidStack;
        getFluidTank(arg0: number, arg1: $Direction_): $IExtendedFluidTank;
        getTankCapacity(arg0: number, arg1: $Direction_): number;
        isFluidValid(arg0: number, arg1: $FluidStack_, arg2: $Direction_): boolean;
        extractFluid(arg0: number, arg1: $Direction_, arg2: $Action_): $FluidStack;
        extractFluid(arg0: $FluidStack_, arg1: $Direction_, arg2: $Action_): $FluidStack;
        extractFluid(arg0: number, arg1: number, arg2: $Direction_, arg3: $Action_): $FluidStack;
        setFluidInTank(arg0: number, arg1: $FluidStack_, arg2: $Direction_): void;
        insertFluid(arg0: number, arg1: $FluidStack_, arg2: $Direction_, arg3: $Action_): $FluidStack;
        insertFluid(arg0: $FluidStack_, arg1: $Direction_, arg2: $Action_): $FluidStack;
        extractEnergy(arg0: number, arg1: number, arg2: $Direction_, arg3: $Action_): number;
        extractEnergy(arg0: number, arg1: $Direction_, arg2: $Action_): number;
        getEnergyContainerCount(arg0: $Direction_): number;
        setEnergy(arg0: number, arg1: number, arg2: $Direction_): void;
        getEnergy(arg0: number, arg1: $Direction_): number;
        getMaxEnergy(arg0: number, arg1: $Direction_): number;
        getEnergyContainer(arg0: number, arg1: $Direction_): $IEnergyContainer;
        getNeededEnergy(arg0: number, arg1: $Direction_): number;
        simulate(): $HeatAPI$HeatTransfer;
        simulateAdjacent(): number;
        incrementAdjacentTransfer(currentAdjacentTransfer: number, tempToTransfer: number, side: $Direction_): number;
        simulateEnvironment(): number;
        updateHeatCapacitors(side: $Direction_): void;
        isValid(arg0: number, arg1: $ChemicalStack, arg2: $Direction_): boolean;
        setChemicalInTank(arg0: number, arg1: $ChemicalStack, arg2: $Direction_): void;
        insertChemical(arg0: $ChemicalStack, arg1: $Direction_, arg2: $Action_): $ChemicalStack;
        insertChemical(arg0: number, arg1: $ChemicalStack, arg2: $Direction_, arg3: $Action_): $ChemicalStack;
        getChemicalInTank(arg0: number, arg1: $Direction_): $ChemicalStack;
        extractChemical(arg0: number, arg1: number, arg2: $Direction_, arg3: $Action_): $ChemicalStack;
        extractChemical(arg0: $ChemicalStack, arg1: $Direction_, arg2: $Action_): $ChemicalStack;
        extractChemical(arg0: number, arg1: $Direction_, arg2: $Action_): $ChemicalStack;
        getCountChemicalTanks(arg0: $Direction_): number;
        getChemicalTankCapacity(arg0: number, arg1: $Direction_): number;
        getChemicalTank(arg0: number, arg1: $Direction_): $IChemicalTank;
        isComputerCapabilityPersistent(): boolean;
        getRadiationParticleCount(): number;
        hasCustomName(): boolean;
        getStackInSlot(arg0: number): $ItemStack;
        getInventorySideFor(): $Direction;
        insertItem(arg0: number, arg1: $ItemStack_, arg2: boolean): $ItemStack;
        getSlots(): number;
        extractItem(arg0: number, arg1: number, arg2: boolean): $ItemStack;
        setStackInSlot(arg0: number, arg1: $ItemStack_): void;
        isItemValid(arg0: number, arg1: $ItemStack_): boolean;
        getSlotLimit(arg0: number): number;
        supportsUpgrade(upgradeType: $Upgrade): boolean;
        getTanks(): number;
        getFluidInTank(arg0: number): $FluidStack;
        getTankCapacity(arg0: number): number;
        isFluidValid(arg0: number, arg1: $FluidStack_): boolean;
        getFluidSideFor(): $Direction;
        extractFluid(arg0: number, arg1: number, arg2: $Action_): $FluidStack;
        setFluidInTank(arg0: number, arg1: $FluidStack_): void;
        insertFluid(arg0: number, arg1: $FluidStack_, arg2: $Action_): $FluidStack;
        extractEnergy(arg0: number, arg1: number, arg2: $Action_): number;
        getEnergyContainerCount(): number;
        setEnergy(arg0: number, arg1: number): void;
        getEnergy(arg0: number): number;
        getMaxEnergy(arg0: number): number;
        getNeededEnergy(arg0: number): number;
        insertEnergy(arg0: number, arg1: number, arg2: $Action_): number;
        getEnergySideFor(): $Direction;
        handleHeat(arg0: number, arg1: $Direction_): void;
        handleHeat(arg0: number, arg1: number, arg2: $Direction_): void;
        getInverseInsulation(arg0: number, arg1: $Direction_): number;
        getHeatCapacitorCount(arg0: $Direction_): number;
        getTotalInverseInsulation(arg0: $Direction_): number;
        getTotalTemperature(arg0: $Direction_): number;
        getInverseConduction(arg0: number, arg1: $Direction_): number;
        getTotalHeatCapacity(arg0: $Direction_): number;
        getTotalInverseConductionCoefficient(arg0: $Direction_): number;
        getTemperature(arg0: number, arg1: $Direction_): number;
        getHeatCapacitor(arg0: number, arg1: $Direction_): $IHeatCapacitor;
        getHeatCapacity(arg0: number, arg1: $Direction_): number;
        isValid(arg0: number, arg1: $ChemicalStack): boolean;
        getSideFor(): $Direction;
        setChemicalInTank(arg0: number, arg1: $ChemicalStack): void;
        insertChemical(arg0: number, arg1: $ChemicalStack, arg2: $Action_): $ChemicalStack;
        getChemicalTanks(): number;
        getChemicalInTank(arg0: number): $ChemicalStack;
        extractChemical(arg0: number, arg1: number, arg2: $Action_): $ChemicalStack;
        getChemicalTankCapacity(arg0: number): number;
        ownerMatches(arg0: $Player): boolean;
        /**
         * @deprecated
         */
        fill(arg0: $FluidStack_, arg1: $IFluidHandler$FluidAction_): number;
        /**
         * @deprecated
         */
        drain(arg0: number, arg1: $IFluidHandler$FluidAction_): $FluidStack;
        /**
         * @deprecated
         */
        drain(arg0: $FluidStack_, arg1: $IFluidHandler$FluidAction_): $FluidStack;
        extractFluid(arg0: $FluidStack_, arg1: $Action_): $FluidStack;
        extractFluid(arg0: number, arg1: $Action_): $FluidStack;
        insertFluid(arg0: $FluidStack_, arg1: $Action_): $FluidStack;
        extractEnergy(arg0: number, arg1: $Action_): number;
        insertEnergy(arg0: number, arg1: $Action_): number;
        handleHeat(arg0: number, arg1: number): void;
        handleHeat(arg0: number): void;
        getTotalInverseConduction(): number;
        getHeatCapacitorCount(): number;
        getTotalTemperature(): number;
        getInverseConduction(arg0: number): number;
        getTotalHeatCapacity(): number;
        getTemperature(arg0: number): number;
        getHeatSideFor(): $Direction;
        getHeatCapacity(arg0: number): number;
        insertChemical(arg0: $ChemicalStack, arg1: $Action_): $ChemicalStack;
        extractChemical(arg0: $ChemicalStack, arg1: $Action_): $ChemicalStack;
        extractChemical(arg0: number, arg1: $Action_): $ChemicalStack;
        kjs$self(): $IItemHandler;
        kjs$getBlock(level: $Level_): $LevelBlock;
        kjs$isMutable(): boolean;
        kjs$setStackInSlot(slot: number, stack: $ItemStack_): void;
        clear(): void;
        clear(match: $ItemPredicate_): void;
        find(match: $ItemPredicate_): number;
        find(): number;
        count(): number;
        count(match: $ItemPredicate_): number;
        asContainer(): $Container;
        getWidth(): number;
        getHeight(): number;
        insertItem(stack: $ItemStack_, simulate: boolean): $ItemStack;
        countNonEmpty(): number;
        countNonEmpty(match: $ItemPredicate_): number;
        setChanged(): void;
        getAllItems(): $List<$ItemStack>;
        isEmpty(): boolean;
        getStackInSlot(slot: number): $ItemStack;
        insertItem(slot: number, stack: $ItemStack_, simulate: boolean): $ItemStack;
        getSlots(): number;
        extractItem(slot: number, amount: number, simulate: boolean): $ItemStack;
        getSlotLimit(slot: number): number;
        isItemValid(slot: number, stack: $ItemStack_): boolean;
        static ITEM_HANDLER_PROVIDER: $ICapabilityProvider<$CapabilityTileEntity, $Direction, $IItemHandler>;
        ticker: number;
        static FLUID_HANDLER_PROVIDER: $ICapabilityProvider<$CapabilityTileEntity, $Direction, $IFluidHandler>;
        facingSupplier: $Supplier<$Direction>;
        static CHEMICAL_HANDLER_PROVIDER: $ICapabilityProvider<$CapabilityTileEntity, $Direction, $IChemicalHandler>;
        static HEAT_HANDLER_PROVIDER: $ICapabilityProvider<$CapabilityTileEntity, $Direction, $IHeatHandler>;
        static ATTACHMENTS_NBT_KEY: string;
        playersUsing: $Set<$Player>;
        constructor(blockProvider: $Holder_<$Block>, pos: $BlockPos_, state: $BlockState_);
        get name(): $Component;
        get displayName(): $Component;
        get component(): $TileComponentUpgrade;
        get currentRedstoneLevel(): number;
        get computerName(): string;
        get powered(): boolean;
        get legacyInfuseTanks(): $List<$IChemicalTank>;
        get legacySlurryTanks(): $List<$IChemicalTank>;
        get legacyPigmentTanks(): $List<$IChemicalTank>;
        get configurationDataType(): $Block;
        get redstoneActivated(): boolean;
        get supportedUpgrade(): $Set<$Upgrade>;
        get activatable(): boolean;
        get direction(): $Direction;
        get blockHolder(): $Holder<$Block>;
        get directional(): boolean;
        get redstoneLevel(): number;
        get frequencyComponent(): $TileComponentFrequency;
        get nameable(): boolean;
        get legacyGasTanks(): $List<$IChemicalTank>;
        get inputRate(): number;
        get security(): $TileComponentSecurity;
        get radiationScale(): number;
        get oppositeDirection(): $Direction;
        get rightSide(): $Direction;
        get leftSide(): $Direction;
        get configCardName(): string;
        get volume(): number;
        get soundCategory(): $SoundSource;
        get soundPos(): $BlockPos;
        get initialVolume(): number;
        get ownerName(): string;
        get computerCapabilityPersistent(): boolean;
        get radiationParticleCount(): number;
        get inventorySideFor(): $Direction;
        get fluidSideFor(): $Direction;
        get energySideFor(): $Direction;
        get sideFor(): $Direction;
        get totalInverseConduction(): number;
        get heatSideFor(): $Direction;
        get width(): number;
        get height(): number;
        get allItems(): $List<$ItemStack>;
        get empty(): boolean;
    }
    export class $CapabilityTileEntity extends $TileEntityUpdateable {
        static basicCapabilityProvider<CAP>(capability: $BlockCapability<CAP, $Direction_>): $ICapabilityProvider<$CapabilityTileEntity, $Direction, CAP>;
        invalidateCapabilityAll(capability: $BlockCapability<never, $Direction_>): void;
        invalidateCapability(capability: $BlockCapability<never, $Direction_>, side: $Direction_): void;
        invalidateCapabilitiesAll(capabilities: $Collection_<$BlockCapability<never, $Direction_>>): void;
        invalidateCapabilitiesFull(): void;
        invalidateCapabilities(capabilities: $Collection_<$BlockCapability<never, $Direction_>>, side: $Direction_): void;
        static capabilityProvider<TILE extends $CapabilityTileEntity, CAP>(capability: $BlockCapability<CAP, $Direction_>, resolverGetter: $BiFunction_<TILE, $BlockCapability<CAP, $Direction>, $ICapabilityResolver<$Direction>>): $ICapabilityProvider<TILE, $Direction, CAP>;
        static ITEM_HANDLER_PROVIDER: $ICapabilityProvider<$CapabilityTileEntity, $Direction, $IItemHandler>;
        static FLUID_HANDLER_PROVIDER: $ICapabilityProvider<$CapabilityTileEntity, $Direction, $IFluidHandler>;
        static CHEMICAL_HANDLER_PROVIDER: $ICapabilityProvider<$CapabilityTileEntity, $Direction, $IChemicalHandler>;
        static HEAT_HANDLER_PROVIDER: $ICapabilityProvider<$CapabilityTileEntity, $Direction, $IHeatHandler>;
        static ATTACHMENTS_NBT_KEY: string;
        constructor(type: $TileEntityTypeRegistryObject<never>, pos: $BlockPos_, state: $BlockState_);
    }
}
