plugins {
    id 'java-library'
    id 'net.neoforged.moddev' version '2.0.143'
}

version = mod_version
group = mod_group_id

base {
    archivesName = 'mekanism-overclock'
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

repositories {
    mavenCentral()
}

neoForge {
    version = project.neo_version

    runs {
        client {
            client()
        }
        server {
            server()
            programArgument '--nogui'
        }
        configureEach {
            logLevel = org.slf4j.event.Level.INFO
        }
    }

    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }
}

dependencies {
    implementation files("${rootProject.projectDir}/../../minecraft/mods/Mekanism-${minecraft_version}-${mekanism_version}.jar")

    testImplementation platform('org.junit:junit-bom:5.11.4')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test', Test).configure {
    useJUnitPlatform()
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 21
}

var generateModMetadata = tasks.register('generateModMetadata', ProcessResources) {
    var replaceProperties = [
        minecraft_version: minecraft_version,
        minecraft_version_range: minecraft_version_range,
        neo_version: neo_version,
        loader_version_range: loader_version_range,
        mekanism_version: mekanism_version,
        mekanism_mod_version_range: mekanism_mod_version_range,
        mod_id: mod_id,
        mod_name: mod_name,
        mod_license: mod_license,
        mod_version: mod_version,
    ]
    inputs.properties replaceProperties
    expand replaceProperties
    from 'src/main/templates'
    into 'build/generated/sources/modMetadata'
}

sourceSets.main.resources.srcDir generateModMetadata
neoForge.ideSyncTask generateModMetadata

tasks.named('jar', Jar).configure {
    manifest {
        attributes([
            'Specification-Title': mod_name,
            'Specification-Version': mod_version,
            'Implementation-Title': mod_name,
            'Implementation-Version': mod_version,
        ])
    }
}

tasks.named('wrapper', Wrapper).configure {
    gradleVersion = '9.2.1'
    distributionType = Wrapper.DistributionType.BIN
}
