org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.230
neo_version_range=[21.1.230,)
loader_version_range=[4,)
mekanism_version=10.7.19.85
mekanism_mod_version_range=[10.7.19,10.8)

mod_id=mekanism_overclock
mod_name=Mekanism Overclock
mod_license=MIT
mod_version=0.1.2
mod_group_id=dev.mekanismoverclock
