import { $Level } from "@package/net/minecraft/world/level";
import { $ItemStack } from "@package/net/minecraft/world/item";
import { $ITerminalStorageTabClient, $ITerminalStorageTabCommon$IVariableInventory, $ITerminalStorageTabCommon, $ITerminalStorageTabServer, $ITerminalStorageTabCommon$ISlotPositionCallback } from "@package/org/cyclops/integratedterminals/api/terminalstorage";
import { $IVariable } from "@package/org/cyclops/integrateddynamics/api/evaluate/variable";
import { $Tag_, $CompoundTag, $CompoundTag_, $Tag } from "@package/net/minecraft/nbt";
import { $Pair } from "@package/org/apache/commons/lang3/tuple";
import { $ITerminalStorageLocation } from "@package/org/cyclops/integratedterminals/api/terminalstorage/location";
import { $Player, $Inventory } from "@package/net/minecraft/world/entity/player";
import { $List, $Map } from "@package/java/util";
import { $ContainerScreenTerminalStorage } from "@package/org/cyclops/integratedterminals/client/gui/container";
import { $HolderLookup$Provider, $NonNullList } from "@package/net/minecraft/core";
import { $INetwork } from "@package/org/cyclops/integrateddynamics/api/network";
import { $FriendlyByteBuf } from "@package/net/minecraft/network";
import { $CraftingOptionGuiData } from "@package/org/cyclops/integratedterminals/core/client/gui";
import { $InventoryContainer } from "@package/org/cyclops/cyclopscore/inventory/container";
import { $Slot, $ContainerSynchronizer, $MenuType_, $ContainerListener } from "@package/net/minecraft/world/inventory";
import { $IDirtyMarkListener, $IDirtyMarkListener_ } from "@package/org/cyclops/cyclopscore/persist";

declare module "@package/org/cyclops/integratedterminals/inventory/container" {
    export class $ContainerTerminalStorageBase$InitTabData {
        getChannel(): number;
        static readFromPacketBuffer(arg0: $FriendlyByteBuf): $ContainerTerminalStorageBase$InitTabData;
        getTabName(): string;
        writeToPacketBuffer(arg0: $FriendlyByteBuf): void;
        constructor(arg0: string, arg1: number);
        get channel(): number;
        get tabName(): string;
    }
    export class $TerminalStorageState {
        getTag(): $CompoundTag;
        setButton(arg0: string, arg1: string, arg2: $Tag_ | null): void;
        static getPlayerDefault(arg0: $Player, arg1: $IDirtyMarkListener_): $TerminalStorageState;
        setTab(arg0: string | null): void;
        static readFromPacketBuffer(arg0: $FriendlyByteBuf): $TerminalStorageState;
        setTag(arg0: $CompoundTag_): void;
        writeToPacketBuffer(arg0: $FriendlyByteBuf): void;
        getTab(): string;
        getSearch(arg0: string, arg1: number): string;
        getButton(arg0: string, arg1: string): $Tag;
        setSearch(arg0: string, arg1: number, arg2: string | null): void;
        hasTab(): boolean;
        setDirtyMarkListener(arg0: $IDirtyMarkListener_): void;
        static setPlayerDefault(arg0: $Player, arg1: $TerminalStorageState): void;
        hasSearch(arg0: string, arg1: number): boolean;
        hasButton(arg0: string, arg1: string): boolean;
        static SETTING_BUTTON: string;
        static SETTING_TAB: string;
        static SETTING_SEARCH: string;
        static PLAYER_TAG_DEFAULT_KEY: string;
        constructor(arg0: $IDirtyMarkListener_);
        constructor(arg0: $CompoundTag_, arg1: $IDirtyMarkListener_);
        set dirtyMarkListener(value: $IDirtyMarkListener_);
    }
    export class $ContainerTerminalStorageBase<L> extends $InventoryContainer implements $IDirtyMarkListener {
        getLocation(): $ITerminalStorageLocation<L>;
        getWorld(): $Level;
        getNetwork(): ($INetwork) | undefined;
        getLocationInstance(): L;
        onDirty(): void;
        getVariableInventory(): ($ITerminalStorageTabCommon$IVariableInventory) | undefined;
        setSelectedTab(arg0: string | null): void;
        getGuiState(): $TerminalStorageState;
        getSelectedChannel(): number;
        onVariableContentsUpdated(arg0: $INetwork, arg1: $IVariable<never>): void;
        sendGuiStateToServer(): void;
        refreshChannelStrings(): void;
        getSelectedTab(): string;
        getChannelStrings(): $List<string>;
        getTabsClientCount(): number;
        getTabCommon(arg0: string): $ITerminalStorageTabCommon;
        getTabsCommon(): $Map<string, $ITerminalStorageTabCommon>;
        getTabsClient(): $Map<string, $ITerminalStorageTabClient<never>>;
        setSelectedChannel(arg0: number): void;
        getTabSlots(arg0: string): $List<$Pair<$Slot, $ITerminalStorageTabCommon$ISlotPositionCallback>>;
        getTabClient(arg0: string): $ITerminalStorageTabClient<any>;
        getTabServer(arg0: string): $ITerminalStorageTabServer;
        getTabsServer(): $Map<string, $ITerminalStorageTabServer>;
        getNextValueId(): number;
        sendOpenCraftingPlanGuiPacketToServer<T, M, L>(arg0: $HolderLookup$Provider, arg1: $CraftingOptionGuiData<T, M, L>): void;
        sendOpenCraftingJobAmountGuiPacketToServer<T, M, L>(arg0: $HolderLookup$Provider, arg1: $CraftingOptionGuiData<T, M, L>): void;
        stateId: number;
        static QUICKCRAFT_HEADER_START: number;
        remoteSlots: $NonNullList<$ItemStack>;
        screen: $ContainerScreenTerminalStorage<any, any>;
        lastSlots: $NonNullList<$ItemStack>;
        static QUICKCRAFT_HEADER_CONTINUE: number;
        static QUICKCRAFT_TYPE_CLONE: number;
        static QUICKCRAFT_TYPE_GREEDY: number;
        static QUICKCRAFT_HEADER_END: number;
        slots: $NonNullList<$Slot>;
        static CARRIED_SLOT_SIZE: number;
        static SLOT_CLICKED_OUTSIDE: number;
        synchronizer: $ContainerSynchronizer;
        containerListeners: $List<$ContainerListener>;
        static BUTTON_SET_DEFAULTS: string;
        containerId: number;
        static QUICKCRAFT_TYPE_CHARITABLE: number;
        constructor(arg0: $MenuType_<never> | null, arg1: number, arg2: $Inventory, arg3: ($ContainerTerminalStorageBase$InitTabData) | undefined, arg4: $TerminalStorageState, arg5: ($INetwork) | undefined, arg6: ($ITerminalStorageTabCommon$IVariableInventory) | undefined);
        get location(): $ITerminalStorageLocation<L>;
        get world(): $Level;
        get network(): ($INetwork) | undefined;
        get locationInstance(): L;
        get variableInventory(): ($ITerminalStorageTabCommon$IVariableInventory) | undefined;
        get guiState(): $TerminalStorageState;
        get channelStrings(): $List<string>;
        get tabsClientCount(): number;
        get tabsCommon(): $Map<string, $ITerminalStorageTabCommon>;
        get tabsClient(): $Map<string, $ITerminalStorageTabClient<never>>;
        get tabsServer(): $Map<string, $ITerminalStorageTabServer>;
        get nextValueId(): number;
    }
}
