import { $NewRegistryEvent } from "@package/net/neoforged/neoforge/registries";
import { $Supplier } from "@package/java/util/function";
import { $Registry } from "@package/net/minecraft/core";
import { $ItemStack_ } from "@package/net/minecraft/world/item";
import { $IEventBus } from "@package/net/neoforged/bus/api";
import { $NoneSpell } from "@package/io/redspace/ironsspellbooks/spells";
import { $ResourceLocation_, $ResourceKey, $ResourceLocation } from "@package/net/minecraft/resources";
import { $SchoolType_, $SchoolType, $AbstractSpell } from "@package/io/redspace/ironsspellbooks/api/spells";
import { $List } from "@package/java/util";

declare module "@package/io/redspace/ironsspellbooks/api/registry" {
    export class $SpellRegistry {
        static register(arg0: $IEventBus): void;
        static none(): $NoneSpell;
        static getEnabledSpells(): $List<$AbstractSpell>;
        static getSpellsForSchool(arg0: $SchoolType_): $List<$AbstractSpell>;
        static onConfigReload(): void;
        static getSpell(arg0: $ResourceLocation_): $AbstractSpell;
        static getSpell(arg0: string): $AbstractSpell;
        static registerRegistry(arg0: $NewRegistryEvent): void;
        static MAGIC_ARROW_SPELL: $Supplier<$AbstractSpell>;
        static SHOCKWAVE_SPELL: $Supplier<$AbstractSpell>;
        static CLEANSE_SPELL: $Supplier<$AbstractSpell>;
        static HEARTSTOP_SPELL: $Supplier<$AbstractSpell>;
        static CHARGE_SPELL: $Supplier<$AbstractSpell>;
        static SUMMON_HORSE_SPELL: $Supplier<$AbstractSpell>;
        static MAGMA_BOMB_SPELL: $Supplier<$AbstractSpell>;
        static ICE_BLOCK_SPELL: $Supplier<$AbstractSpell>;
        static ABYSSAL_SHROUD_SPELL: $Supplier<$AbstractSpell>;
        static DEVOUR_SPELL: $Supplier<$AbstractSpell>;
        static GUIDING_BOLT_SPELL: $Supplier<$AbstractSpell>;
        static FANG_STRIKE_SPELL: $Supplier<$AbstractSpell>;
        static FLAMING_STRIKE_SPELL: $Supplier<$AbstractSpell>;
        static BURNING_DASH_SPELL: $Supplier<$AbstractSpell>;
        static FROSTWAVE_SPELL: $Supplier<$AbstractSpell>;
        static SACRIFICE_SPELL: $Supplier<$AbstractSpell>;
        static PORTAL_SPELL: $Supplier<$AbstractSpell>;
        static BLOOD_SLASH_SPELL: $Supplier<$AbstractSpell>;
        static ANGEL_WINGS_SPELL: $Supplier<$AbstractSpell>;
        static SUMMON_SWORDS: $Supplier<$AbstractSpell>;
        static SONIC_BOOM_SPELL: $Supplier<$AbstractSpell>;
        static ELDRITCH_BLAST_SPELL: $Supplier<$AbstractSpell>;
        static LOB_CREEPER_SPELL: $Supplier<$AbstractSpell>;
        static WOLOLO_SPELL: $Supplier<$AbstractSpell>;
        static BALL_LIGHTNING_SPELL: $Supplier<$AbstractSpell>;
        static BLOOD_STEP_SPELL: $Supplier<$AbstractSpell>;
        static SHADOW_SLASH: $Supplier<$AbstractSpell>;
        static SCULK_TENTACLES_SPELL: $Supplier<$AbstractSpell>;
        static ACID_ORB_SPELL: $Supplier<$AbstractSpell>;
        static WISP_SPELL: $Supplier<$AbstractSpell>;
        static DRAGON_BREATH_SPELL: $Supplier<$AbstractSpell>;
        static FANG_WARD_SPELL: $Supplier<$AbstractSpell>;
        static SNOWBALL_SPELL: $Supplier<$AbstractSpell>;
        static GREATER_HEAL_SPELL: $Supplier<$AbstractSpell>;
        static HEALING_CIRCLE_SPELL: $Supplier<$AbstractSpell>;
        static FIREBOLT_SPELL: $Supplier<$AbstractSpell>;
        static DIVINE_SMITE_SPELL: $Supplier<$AbstractSpell>;
        static THUNDERSTORM_SPELL: $Supplier<$AbstractSpell>;
        static SPELL_REGISTRY_KEY: $ResourceKey<$Registry<$AbstractSpell>>;
        static ECHOING_STRIKES_SPELL: $Supplier<$AbstractSpell>;
        static SUMMON_VEX_SPELL: $Supplier<$AbstractSpell>;
        static ICICLE_SPELL: $Supplier<$AbstractSpell>;
        static SUNBEAM_SPELL: $Supplier<$AbstractSpell>;
        static POISON_ARROW_SPELL: $Supplier<$AbstractSpell>;
        static THROW_SPELL: $Supplier<$AbstractSpell>;
        static BLAZE_STORM_SPELL: $Supplier<$AbstractSpell>;
        static FIRE_ARROW_SPELL: $Supplier<$AbstractSpell>;
        static RAY_OF_SIPHONING_SPELL: $Supplier<$AbstractSpell>;
        static ICE_SPIKES_SPELL: $Supplier<$AbstractSpell>;
        static SCORCH_SPELL: $Supplier<$AbstractSpell>;
        static ELECTROCUTE_SPELL: $Supplier<$AbstractSpell>;
        static ACUPUNCTURE_SPELL: $Supplier<$AbstractSpell>;
        static RECALL_SPELL: $Supplier<$AbstractSpell>;
        static CHAIN_CREEPER_SPELL: $Supplier<$AbstractSpell>;
        static GLUTTONY_SPELL: $Supplier<$AbstractSpell>;
        static EVASION_SPELL: $Supplier<$AbstractSpell>;
        static ASCENSION_SPELL: $Supplier<$AbstractSpell>;
        static SUMMON_ENDER_CHEST_SPELL: $Supplier<$AbstractSpell>;
        static HEAL_SPELL: $Supplier<$AbstractSpell>;
        static ARROW_VOLLEY_SPELL: $Supplier<$AbstractSpell>;
        static INVISIBILITY_SPELL: $Supplier<$AbstractSpell>;
        static BLESSING_OF_LIFE_SPELL: $Supplier<$AbstractSpell>;
        static FORTIFY_SPELL: $Supplier<$AbstractSpell>;
        static SHIELD_SPELL: $Supplier<$AbstractSpell>;
        static WITHER_SKULL_SPELL: $Supplier<$AbstractSpell>;
        static SUMMON_POLAR_BEAR_SPELL: $Supplier<$AbstractSpell>;
        static FIREFLY_SWARM_SPELL: $Supplier<$AbstractSpell>;
        static TOUCH_DIG: $Supplier<$AbstractSpell>;
        static VOLT_STRIKE_SPELL: $Supplier<$AbstractSpell>;
        static POCKET_DIMENSION_SPELL: $Supplier<$AbstractSpell>;
        static FIREBALL_SPELL: $Supplier<$AbstractSpell>;
        static WALL_OF_FIRE_SPELL: $Supplier<$AbstractSpell>;
        static MAGIC_MISSILE_SPELL: $Supplier<$AbstractSpell>;
        static CHAIN_LIGHTNING_SPELL: $Supplier<$AbstractSpell>;
        static BLOOD_NEEDLES_SPELL: $Supplier<$AbstractSpell>;
        static RAY_OF_FROST_SPELL: $Supplier<$AbstractSpell>;
        static STOMP_SPELL: $Supplier<$AbstractSpell>;
        static STARFALL_SPELL: $Supplier<$AbstractSpell>;
        static SPECTRAL_HAMMER_SPELL: $Supplier<$AbstractSpell>;
        static FROST_STEP_SPELL: $Supplier<$AbstractSpell>;
        static OAKSKIN_SPELL: $Supplier<$AbstractSpell>;
        static BLIGHT_SPELL: $Supplier<$AbstractSpell>;
        static FLAMING_BARRAGE_SPELL: $Supplier<$AbstractSpell>;
        static CONE_OF_COLD_SPELL: $Supplier<$AbstractSpell>;
        static FIRE_BREATH_SPELL: $Supplier<$AbstractSpell>;
        static LIGHTNING_BOLT_SPELL: $Supplier<$AbstractSpell>;
        static CLOUD_OF_REGENERATION_SPELL: $Supplier<$AbstractSpell>;
        static POISON_SPLASH_SPELL: $Supplier<$AbstractSpell>;
        static SPIDER_ASPECT_SPELL: $Supplier<$AbstractSpell>;
        static REGISTRY: $Registry<$AbstractSpell>;
        static PLANAR_SIGHT_SPELL: $Supplier<$AbstractSpell>;
        static RAISE_DEAD_SPELL: $Supplier<$AbstractSpell>;
        static ICE_TOMB_SPELL: $Supplier<$AbstractSpell>;
        static COUNTERSPELL_SPELL: $Supplier<$AbstractSpell>;
        static RAISE_HELL_SPELL: $Supplier<$AbstractSpell>;
        static POISON_BREATH_SPELL: $Supplier<$AbstractSpell>;
        static HASTE_SPELL: $Supplier<$AbstractSpell>;
        static SLOW_SPELL: $Supplier<$AbstractSpell>;
        static HEAT_SURGE_SPELL: $Supplier<$AbstractSpell>;
        static EARTHQUAKE_SPELL: $Supplier<$AbstractSpell>;
        static ROOT_SPELL: $Supplier<$AbstractSpell>;
        static BLACK_HOLE_SPELL: $Supplier<$AbstractSpell>;
        static LIGHTNING_LANCE_SPELL: $Supplier<$AbstractSpell>;
        static GUST_SPELL: $Supplier<$AbstractSpell>;
        static FROSTBITE_SPELL: $Supplier<$AbstractSpell>;
        static FIRECRACKER_SPELL: $Supplier<$AbstractSpell>;
        static TELEKINESIS_SPELL: $Supplier<$AbstractSpell>;
        static TELEPORT_SPELL: $Supplier<$AbstractSpell>;
        constructor();
        static get enabledSpells(): $List<$AbstractSpell>;
    }
    export class $SchoolRegistry {
        static register(arg0: $IEventBus): void;
        static getSchoolsFromFocus(arg0: $ItemStack_): $List<$SchoolType>;
        static getSchool(arg0: $ResourceLocation_): $SchoolType;
        static getSchoolFromFocus(arg0: $ItemStack_): $SchoolType;
        static registerRegistry(arg0: $NewRegistryEvent): void;
        static ENDER_RESOURCE: $ResourceLocation;
        static BLOOD_RESOURCE: $ResourceLocation;
        static ELDRITCH_RESOURCE: $ResourceLocation;
        static EVOCATION: $Supplier<$SchoolType>;
        static LIGHTNING_RESOURCE: $ResourceLocation;
        static ICE_RESOURCE: $ResourceLocation;
        static FIRE_RESOURCE: $ResourceLocation;
        static LIGHTNING: $Supplier<$SchoolType>;
        static HOLY_RESOURCE: $ResourceLocation;
        static ICE: $Supplier<$SchoolType>;
        static EVOCATION_RESOURCE: $ResourceLocation;
        static NATURE_RESOURCE: $ResourceLocation;
        static NATURE: $Supplier<$SchoolType>;
        static SCHOOL_REGISTRY_KEY: $ResourceKey<$Registry<$SchoolType>>;
        static HOLY: $Supplier<$SchoolType>;
        static FIRE: $Supplier<$SchoolType>;
        static ENDER: $Supplier<$SchoolType>;
        static REGISTRY: $Registry<$SchoolType>;
        static BLOOD: $Supplier<$SchoolType>;
        static ELDRITCH: $Supplier<$SchoolType>;
        constructor();
    }
}
